##' lorem ipsum text
##'
##' @export
lorem <- "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec molestie risus. Duis vitae eros odio. Proin condimentum odio dolor, at vehicula lorem tempus sit amet. Nunc id metus vehicula, facilisis velit in, tincidunt augue. Donec at semper turpis, nec cursus justo. Suspendisse est lorem, vulputate vitae diam sit amet, luctus volutpat sem. Aenean at odio sed nibh tempor eleifend. Duis ultrices turpis sit amet velit luctus, eu commodo urna lacinia. In porttitor tristique quam ac molestie. In sit amet lacinia enim. Vivamus nec turpis sed leo viverra faucibus vel sit amet velit. Pellentesque egestas tellus nec augue condimentum sagittis.

Proin posuere, massa eu ornare venenatis, leo ligula faucibus tortor, quis congue est nibh non felis. Curabitur erat turpis, ullamcorper vitae dui ac, consectetur mollis nisi. Proin condimentum velit ut sem tempor malesuada. Aliquam rutrum fringilla semper. Sed aliquam eleifend tortor eget laoreet. Nullam adipiscing et tortor at venenatis. Fusce adipiscing sem at libero egestas tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget luctus dui. In congue faucibus ligula, eu venenatis urna pretium id. Duis sit amet elit ac justo laoreet vehicula. Vestibulum lacinia sit amet massa ut adipiscing. Maecenas aliquet erat nibh, eget porttitor sem vulputate vel. Nulla neque nunc, blandit ac leo nec, rutrum faucibus odio. Sed adipiscing lorem semper risus ultrices, vel fringilla nisl venenatis. Suspendisse magna metus, vulputate et tellus sit amet, dapibus posuere nunc.

Integer facilisis pellentesque feugiat. Nullam neque dui, auctor a sagittis ac, consequat nec justo. Maecenas luctus odio vel neque fringilla, bibendum egestas metus bibendum. Nulla vel tortor at eros porttitor gravida ac placerat leo. In hac habitasse platea dictumst. Nam urna sem, ullamcorper eu convallis non, volutpat id elit. Maecenas dictum magna a nisi interdum, id hendrerit arcu blandit. Quisque sollicitudin adipiscing lacus. Phasellus quis aliquam lectus. Etiam nec venenatis tellus.

Ut adipiscing posuere posuere. Nullam id tempus tortor, in rhoncus eros. Nunc vehicula quam eget mi luctus sollicitudin. Ut feugiat convallis nulla, rhoncus ultricies tellus ultricies id. Donec suscipit sapien enim, id lobortis lectus molestie ac. Fusce lacus orci, hendrerit vel mauris dictum, vulputate molestie diam. Maecenas fringilla sapien at auctor sagittis. Maecenas ut ipsum non tortor venenatis consequat. Praesent sit amet odio consectetur, luctus magna in, ultricies risus. Duis eget justo in nulla euismod convallis. Vivamus condimentum condimentum blandit. Sed sollicitudin pellentesque bibendum. Aenean ornare hendrerit risus luctus luctus. Nullam cursus sagittis ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Nullam metus nunc, eleifend quis lacus ut, molestie vestibulum arcu. Curabitur sed dapibus libero. In in ullamcorper elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque egestas lorem quis lectus ullamcorper, a placerat urna mollis. Nunc sodales, nunc non rutrum molestie, nisi est convallis nunc, et tempor velit lacus et ipsum. Donec vitae scelerisque turpis. Mauris et laoreet metus. Sed lobortis hendrerit eros, eget sollicitudin urna luctus interdum. Suspendisse pellentesque facilisis ligula et pulvinar. Vivamus tincidunt posuere sem, non tempor nulla tristique nec. Nam non venenatis nulla, sed facilisis libero. Etiam rutrum mattis nisl id mollis. Curabitur sed porta nunc. Nulla bibendum euismod ultricies. Maecenas ullamcorper dolor vitae massa ullamcorper gravida.

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
