# CIE 1931 xy Chromaticity Diagram + CIE 1976 u'v' Chromaticity Diagram + CIE 1960 uv Chromaticity Diagram
# with confusion vectors

source('/home/poky/Desktop/z4/color deficiencies/CVDdev.R')
par(mfrow=c(1,3))
chromaticity.diagram.color.fill (xlim=c(0,.8), ylim=c(0,.8),main="Confusion vectors CIE 1931 xy")
plotConfusionVectors(lengthPDT=.3)
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1976uv, xlim=c(0,.8), ylim=c(0,.6), xlab="u'",ylab="v'",main="Confusion vectors CIE 1976 u'v'")
plotConfusionVectors('CIE1976uv',lengthPDT=.3)
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1960uv, xlim=c(0,.8), ylim=c(0,.6), xlab="u'",ylab="v'",main="Confusion vectors CIE 1960 uv")
plotConfusionVectors('CIE1960uv',lengthPDT=.3)
stop()


par(mfrow=c(5,3))
chromaticity.diagram.color.fill (xlim=c(0,.8), ylim=c(0,.8), xlab="u'",ylab="v'",main="Confusion vectors CIE 1931 xy")
plotConfusionVectors()
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1976uv, xlim=c(0,.8), ylim=c(0,.6), xlab="u'",ylab="v'",main="Confusion vectors CIE 1976 u'v'")
plotConfusionVectors('CIE1976uv')
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1960uv, xlim=c(0,.8), ylim=c(0,.6), xlab="u'",ylab="v'",main="Confusion vectors CIE 1960 uv")
plotConfusionVectors('CIE1960uv')
chromaticity.diagram.color.fill (xlim=c(0,.4), ylim=c(0,.4), xlab="u'",ylab="v'",main="Confusion vectors CIE 1931 xy")
plotConfusionVectors()
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1976uv, xlim=c(0,.4), ylim=c(0,.3), xlab="u'",ylab="v'",main="Confusion vectors CIE 1976 u'v'")
plotConfusionVectors('CIE1976uv')
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1960uv, xlim=c(0,.4), ylim=c(0,.3), xlab="u'",ylab="v'",main="Confusion vectors CIE 1960 uv")
plotConfusionVectors('CIE1960uv')
chromaticity.diagram.color.fill (xlim=c(0,.4), ylim=c(.4,.8), xlab="u'",ylab="v'",main="Confusion vectors CIE 1931 xy")
plotConfusionVectors()
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1976uv, xlim=c(0,.4), ylim=c(.3,.6), xlab="u'",ylab="v'",main="Confusion vectors CIE 1976 u'v'")
plotConfusionVectors('CIE1976uv')
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1960uv, xlim=c(0,.4), ylim=c(.3,.6), xlab="u'",ylab="v'",main="Confusion vectors CIE 1960 uv")
plotConfusionVectors('CIE1960uv')
chromaticity.diagram.color.fill (xlim=c(.4,.8), ylim=c(0,.4), xlab="u'",ylab="v'",main="Confusion vectors CIE 1931 xy")
plotConfusionVectors()
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1976uv, xlim=c(.4,.8), ylim=c(0,.3), xlab="u'",ylab="v'",main="Confusion vectors CIE 1976 u'v'")
plotConfusionVectors('CIE1976uv')
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1960uv, xlim=c(.4,.8), ylim=c(0,.3), xlab="u'",ylab="v'",main="Confusion vectors CIE 1960 uv")
plotConfusionVectors('CIE1960uv')
chromaticity.diagram.color.fill (xlim=c(.4,.8), ylim=c(.4,.8), xlab="u'",ylab="v'",main="Confusion vectors CIE 1931 xy")
plotConfusionVectors()
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1976uv, xlim=c(.4,.8), ylim=c(.3,.6), xlab="u'",ylab="v'",main="Confusion vectors CIE 1976 u'v'")
plotConfusionVectors('CIE1976uv')
chromaticity.diagram.color.fill (conversionFunction=CIE1931XYZ2CIE1960uv, xlim=c(.4,.8), ylim=c(.3,.6), xlab="u'",ylab="v'",main="Confusion vectors CIE 1960 uv")
plotConfusionVectors('CIE1960uv')
