# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getNberCriteria_Rcpp <- function() {
    .Call('ClustMMDD_getNberCriteria_Rcpp', PACKAGE = 'ClustMMDD')
}

getCriteriaNames_Rcpp <- function() {
    .Call('ClustMMDD_getCriteriaNames_Rcpp', PACKAGE = 'ClustMMDD')
}

getNberOccurrencesMax <- function() {
    .Call('ClustMMDD_getNberOccurrencesMax', PACKAGE = 'ClustMMDD')
}

simulProb <- function(n) {
    .Call('ClustMMDD_simulProb', PACKAGE = 'ClustMMDD', n)
}

testFactorial <- function() {
    invisible(.Call('ClustMMDD_testFactorial', PACKAGE = 'ClustMMDD'))
}

cutInN <- function(x, N) {
    .Call('ClustMMDD_cutInN', PACKAGE = 'ClustMMDD', x, N)
}

cutEachColInN <- function(tab, N) {
    .Call('ClustMMDD_cutEachColInN', PACKAGE = 'ClustMMDD', tab, N)
}

howmanyWords <- function(line) {
    .Call('ClustMMDD_howmanyWords', PACKAGE = 'ClustMMDD', line)
}

isComment <- function(ligne) {
    .Call('ClustMMDD_isComment', PACKAGE = 'ClustMMDD', ligne)
}

nberOfLines <- function(fichier) {
    .Call('ClustMMDD_nberOfLines', PACKAGE = 'ClustMMDD', fichier)
}

nberOfColumns <- function(fichier) {
    .Call('ClustMMDD_nberOfColumns', PACKAGE = 'ClustMMDD', fichier)
}

readLineN_R <- function(fichier, n) {
    .Call('ClustMMDD_readLineN_R', PACKAGE = 'ClustMMDD', fichier, n)
}

initialiseEmSettings <- function() {
    invisible(.Call('ClustMMDD_initialiseEmSettings', PACKAGE = 'ClustMMDD'))
}

EmOptionsDefault <- function() {
    invisible(.Call('ClustMMDD_EmOptionsDefault', PACKAGE = 'ClustMMDD'))
}

EmSettings <- function(xepsi = -1.0, xnberSmallEM = -1L, xnberIterations = -1L, xtypeEM = -1L, xtypeSmallEM = -1L, xnberIterLongEM = -1L, xputThreshold = FALSE) {
    invisible(.Call('ClustMMDD_EmSettings', PACKAGE = 'ClustMMDD', xepsi, xnberSmallEM, xnberIterations, xtypeEM, xtypeSmallEM, xnberIterLongEM, xputThreshold))
}

EmOptionsDisplay <- function() {
    invisible(.Call('ClustMMDD_EmOptionsDisplay', PACKAGE = 'ClustMMDD'))
}

getEmOptions_Rcpp <- function() {
    .Call('ClustMMDD_getEmOptions_Rcpp', PACKAGE = 'ClustMMDD')
}

obsFreq <- function(data, n_occurrences, levels, n_levels, levels_freq, classif, S) {
    .Call('ClustMMDD_obsFreq', PACKAGE = 'ClustMMDD', data, n_occurrences, levels, n_levels, levels_freq, classif, S)
}

EM1_Rcpp <- function(tab, n_occurrences, levels, n_levels, levels_count, levels_freq, Cte) {
    .Call('ClustMMDD_EM1_Rcpp', PACKAGE = 'ClustMMDD', tab, n_occurrences, levels, n_levels, levels_count, levels_freq, Cte)
}

mapClassification_Rcpp <- function(Tik) {
    .Call('ClustMMDD_mapClassification_Rcpp', PACKAGE = 'ClustMMDD', Tik)
}

smallEM_Rcpp <- function(tab, n_occurrences, levels, n_levels, levels_count, levels_freq, K, S) {
    .Call('ClustMMDD_smallEM_Rcpp', PACKAGE = 'ClustMMDD', tab, n_occurrences, levels, n_levels, levels_count, levels_freq, K, S)
}

EM_Rcpp <- function(tab, n_occurrences, levels, n_levels, levels_count, levels_freq, K, S, Cte = 1.0) {
    .Call('ClustMMDD_EM_Rcpp', PACKAGE = 'ClustMMDD', tab, n_occurrences, levels, n_levels, levels_count, levels_freq, K, S, Cte)
}

readModelFromString_Rcpp <- function(mod) {
    .Call('ClustMMDD_readModelFromString_Rcpp', PACKAGE = 'ClustMMDD', mod)
}

isInFile_Rcpp <- function(K, S, fichier, header) {
    .Call('ClustMMDD_isInFile_Rcpp', PACKAGE = 'ClustMMDD', K, S, fichier, header)
}

computeCriteria_Rcpp <- function(lv, dim, N, entropy = 0, Cte = 1.0) {
    .Call('ClustMMDD_computeCriteria_Rcpp', PACKAGE = 'ClustMMDD', lv, dim, N, entropy, Cte)
}

computeCriteriaFromFile_Rcpp <- function(xfile, Cte, header, indexes = as.integer( c())) {
    .Call('ClustMMDD_computeCriteriaFromFile_Rcpp', PACKAGE = 'ClustMMDD', xfile, Cte, header, indexes)
}

writeParInFile_Rcpp <- function(x, xfile) {
    invisible(.Call('ClustMMDD_writeParInFile_Rcpp', PACKAGE = 'ClustMMDD', x, xfile))
}

writeModelInFile_Rcpp <- function(x, xfile) {
    invisible(.Call('ClustMMDD_writeModelInFile_Rcpp', PACKAGE = 'ClustMMDD', x, xfile))
}

writeCriteriaInFile_Rcpp <- function(criteria, xfile) {
    invisible(.Call('ClustMMDD_writeCriteriaInFile_Rcpp', PACKAGE = 'ClustMMDD', criteria, xfile))
}

readModelAt_Rcpp <- function(xfile, n, header) {
    .Call('ClustMMDD_readModelAt_Rcpp', PACKAGE = 'ClustMMDD', xfile, n, header)
}

selectDimFromFile_Rcpp <- function(xfileExploredModels, constantGrid, vectLogLik, vectDim, header) {
    .Call('ClustMMDD_selectDimFromFile_Rcpp', PACKAGE = 'ClustMMDD', xfileExploredModels, constantGrid, vectLogLik, vectDim, header)
}

selectDimFromData_Rcpp <- function(xlogLik, xdim, xconstantGrid, outLogLik, outDim) {
    .Call('ClustMMDD_selectDimFromData_Rcpp', PACKAGE = 'ClustMMDD', xlogLik, xdim, xconstantGrid, outLogLik, outDim)
}

dimJump_Rcpp <- function(vectDim, pas, BeginEnd1, BeginEnd2) {
    .Call('ClustMMDD_dimJump_Rcpp', PACKAGE = 'ClustMMDD', vectDim, pas, BeginEnd1, BeginEnd2)
}

selectModelFromFile_Rcpp <- function(xfileExploredModels, vectN, vectK, matS, vectLogLik, vectDim, vectEntropy, vectCriteria, cte, header, lines) {
    invisible(.Call('ClustMMDD_selectModelFromFile_Rcpp', PACKAGE = 'ClustMMDD', xfileExploredModels, vectN, vectK, matS, vectLogLik, vectDim, vectEntropy, vectCriteria, cte, header, lines))
}

selectModelFromData_Rcpp <- function(vectLogLik, vectDim, vectEntropy, N, cte, vectIndexes, vectCriteria) {
    invisible(.Call('ClustMMDD_selectModelFromData_Rcpp', PACKAGE = 'ClustMMDD', vectLogLik, vectDim, vectEntropy, N, cte, vectIndexes, vectCriteria))
}

readParKS_Rcpp <- function(xfile) {
    .Call('ClustMMDD_readParKS_Rcpp', PACKAGE = 'ClustMMDD', xfile)
}

writeParKS_InFile_Rcpp <- function(modelList, file) {
    invisible(.Call('ClustMMDD_writeParKS_InFile_Rcpp', PACKAGE = 'ClustMMDD', modelList, file))
}

