epimem <-
function(i.data,i.type=2,i.level=0.95,i.type.curve=2,i.level.curve=0.95,i.type.threshold=5,i.level.threshold=0.95,i.n.max=-1,i.tails=1,i.type.boot="norm",i.iter.boot=10000,i.method=2,i.param=2.8,i.levels=c(0.40,0.90,0.975),i.seasons=10){
  res<-influenza(i.data,i.type,i.level,i.type.curve,i.level.curve,i.type.threshold,i.level.threshold,i.n.max,i.tails,i.type.boot,i.iter.boot,i.method,i.param,i.levels,i.seasons)
  res.final<-list(
    i.data=res$i.datos,
    pre.post.intervals=res$pre.post.intervalos,
    ci.length=res$ic.duracion,
    ci.percent=res$ic.porcentaje,
    mean.length=res$duracion.media,
    moving.epidemics=res$temporadas.moviles.recortada,
    mean.start=res$ic.inicio[1:2,2],
    epi.intervals=res$epi.intervalos,
    typ.curve=res$curva.tipo,
    n.max=res$n.max,
    param.type=res$parametro.tipo,
    param.level=res$parametro.nivel,
    param.type.curve=res$parametro.tipo.curva,
    param.level.curve=res$parametro.nivel.curva,
    param.type.threshold=res$parametro.tipo.umbral,
    param.level.threshold=res$parametro.nivel.umbral,
    param.method=res$parametro.metodo,
    param.param=res$parametro.parametro,
    param.n.max=res$parametro.n.max,
    param.tails=res$parametro.colas,
    param.levels=res$parametro.niveles,
    param.max.seasons=res$parametro.n.max.temp,
    n.seasons=res$n.temporadas,
    n.weeks=res$n.semanas,
    param.type.boot=res$parametro.tipo.boot,
    param.iter.boot=res$parametro.iteraciones.boot)
  res.final$call<-match.call()
  class(res.final)<-"flu"
  return(res.final)
}
