pathPla <- ".."
pathPla <- system.file(package = "pla")
source(paste(pathPla, "R.xtables/fun.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtabularAssay.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtablesAssay.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableHead.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableLabels.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableLatinSquare.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableTableCS.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableTable.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableModel.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableAnova.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableParameters.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtableValidity.R", sep = "/"))
source(paste(pathPla, "R.xtables/xtablePotency.R", sep = "/"))
