# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeinter_cpp <- function(X00, X10, X20) {
    .Call('sparsereg_makeinter_cpp', PACKAGE = 'sparsereg', X00, X10, X20)
}

makethreeinter_cpp <- function(X00, X10, X110, X20) {
    .Call('sparsereg_makethreeinter_cpp', PACKAGE = 'sparsereg', X00, X10, X110, X20)
}

updatebeta_cpp <- function(X0, y0, betacurr0, betamode0, lambdavec0, dtau0, sigmasq0, ps_sigmasq0, lambdashrink0, k0) {
    .Call('sparsereg_updatebeta_cpp', PACKAGE = 'sparsereg', X0, y0, betacurr0, betamode0, lambdavec0, dtau0, sigmasq0, ps_sigmasq0, lambdashrink0, k0)
}

