clust<-function(h,...){
	f<-function(h,...){
		x<<-svalue(h$obj)
		}

		try(({
		dat2Affy.m<-dat2Affy.m;datAgOne2.m<-datAgOne2.m;datAgTwo2.m<-datAgTwo2.m;datIllBA2.m2<-datIllBA2.m2;
		lumi_NQ.m<-lumi_NQ.m;data.matrix_Nimblegen2.m<-data.matrix_Nimblegen2.m;
		data.matrixNorm.m<-data.matrixNorm.m;data.matrix_onlineNorm.m<-data.matrix_onlineNorm.m;l<-l;tree<-tree;
			}),silent=TRUE)
		platforms=NULL;
		aa=0;bb=0;cc=0;dd=0;ee=0;ff=0;gg=0;hh=0;
		try(({
			if(exists("dat2Affy.m"))aa=length(dat2Affy.m)
			if(exists("datAgOne2.m"))bb=length(datAgOne2.m)
			if(exists("datAgTwo2.m"))cc=length(datAgTwo2.m)
			if(exists("datIllBA2.m2"))dd=length(datIllBA2.m2)
			if(exists("lumi_NQ.m"))ee=length(lumi_NQ.m)
			if(exists("data.matrix_Nimblegen2.m"))ff=length(data.matrix_Nimblegen2.m)
			if(exists("data.matrixNorm.m"))gg=length(data.matrixNorm.m)
			if(exists("data.matrix_onlineNorm.m"))hh=length(data.matrix_onlineNorm.m)
			}),silent=TRUE)
		if(aa!=0)platforms=c(platforms,"Affymetrix")
		if(bb!=0)platforms=c(platforms,"Agilent_OneColor")
		if(cc!=0)platforms=c(platforms,"Agilent_TwoColor")
		if(dd!=0)platforms=c(platforms,"Illumina_Beadarray")
		if(ee!=0)platforms=c(platforms,"Illumina_Lumi")
		if(ff!=0)platforms=c(platforms,"Nimblegen")
		if(gg!=0)platforms=c(platforms,"Series_Matrix")
		if(hh!=0)platforms=c(platforms,"Online_Data")
	
	sample.dist_Affy=NULL;sample.dist_Ag1=NULL;sample.dist_Ag2=NULL;sample.dist_Il_B=NULL;sample.dist_Il_L=NULL;
	sample.dist_N=NULL;sample.dist_S=NULL;sample.dist_O=NULL;
	sample.clust_Affy=NULL;sample.clust_Ag1=NULL;sample.clust_Ag2=NULL;sample.clust_Il_B=NULL;sample.clust_Il_L=NULL;
	sample.clust_N=NULL;sample.clust_S=NULL;sample.clust_O=NULL;
	
	rm(sample.dist_Affy,sample.dist_Ag1,sample.dist_Ag2,sample.dist_Il_B,sample.dist_Il_L,
	sample.dist_N,sample.dist_S,sample.dist_O,
	sample.clust_Affy,sample.clust_Ag1,sample.clust_Ag2,sample.clust_Il_B,sample.clust_Il_L,
	sample.clust_N,sample.clust_S,sample.clust_O)
	
	x=NULL
	z=NULL
	w_dge<-gwindow("Select your data",width=260,height=280,visible=FALSE,horizontal=FALSE)
	gp_dge<-ggroup(container=w_dge,horizontal=FALSE)
	cbg_dge<-gcheckboxgroup(platforms,container=gp_dge,handler=f)
	svalue(cbg_dge,index=FALSE)<-1:8
	
	gp2_dge<-ggroup(container=gp_dge,width=30,height=15,horizontal=TRUE)
	addSpring(gp2_dge)
	y<-gbutton("CANCEL",border=TRUE,handler=function(h,...){
		dispose(w_dge)
	},container=gp2_dge,anchor=c(1,-1))
	y2<-gbutton("OK",border=TRUE,handler=function(h,...){
		if(length(x)!=0){
		if(length(which(x=="Affymetrix"))!=0){
			sample.dist_c1<-dist(t(dat2Affy.m)) 
			sample.dist_Affy<<-as.dist(1-cor(dat2Affy.m,method="pearson"))
			sample.clust_Affy<<-hclust(sample.dist_Affy,method="complete")
			plot(sample.clust_Affy)
			if(length(sample.dist_Affy)!=0){
				visible(g1_1)<-FALSE
				l$Affymetrix$Cluster_Plot<<-list()
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,400)
				visible(g1_1)<-TRUE
				}
				display()
			}
		if(length(which(x=="Agilent_OneColor"))!=0){
			sample.dist_c1<-dist(t(datAgOne2.m)) 
			sample.dist_Ag1<<-as.dist(1-cor(datAgOne2.m,method="pearson"))
			sample.clust_Ag1<<-hclust(sample.dist_Ag1,method="complete")
			plot(sample.clust_Ag1)
			if(length(sample.dist_Ag1)!=0){
				visible(g1_1)<-FALSE
				l$Agilent_OneColor$Cluster_Plot<<-list()
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,400)
				visible(g1_1)<-TRUE
				}
				display()
			}
		if(length(which(x=="Agilent_TwoColor"))!=0){
			sample.dist_c1<-dist(t(datAgTwo2.m)) 
			sample.dist_Ag2<<-as.dist(1-cor(datAgTwo2.m,method="pearson"))
			sample.clust_Ag2<<-hclust(sample.dist_Ag2,method="complete")
			plot(sample.clust_Ag2)
			if(length(sample.dist_Ag2)!=0){
				visible(g1_1)<-FALSE
				l$Agilent_TwoColor$Cluster_Plot<<-list()
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,400)
				visible(g1_1)<-TRUE
				}
				display()
			}
		if(length(which(x=="Illumina_Beadarray"))!=0){
			sample.dist_c1<-dist(t(datIllBA2.m2)) 
			sample.dist_Il_B<<-as.dist(1-cor(datIllBA2.m2,method="pearson"))
			sample.clust_Il_B<<-hclust(sample.dist_Il_B,method="complete")
			plot(sample.clust_Il_B)
			if(length(sample.dist_Il_B)!=0){
				visible(g1_1)<-FALSE
				l$Illumina_Beadarray$Cluster_Plot<<-list()
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,400)
				visible(g1_1)<-TRUE
				}
				display()
			}
		if(length(which(x=="Illumina_Lumi"))!=0){
			sample.dist_c1<-dist(t(lumi_NQ.m)) 
			sample.dist_Il_L<<-as.dist(1-cor(lumi_NQ.m,method="pearson"))
			sample.clust_Il_L<<-hclust(sample.dist_Il_L,method="complete")
			plot(sample.clust_Il_L)
			if(length(sample.dist_Il_L)!=0){
				visible(g1_1)<-FALSE
				l$Illumina_Lumi$Cluster_Plot<<-list()
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,400)
				visible(g1_1)<-TRUE
				}
				display()
			}
		if(length(which(x=="Nimblegen"))!=0){
			sample.dist_c1<-dist(t(data.matrix_Nimblegen2.m)) 
			sample.dist_N<<-as.dist(1-cor(data.matrix_Nimblegen2.m,method="pearson"))
			sample.clust_N<<-hclust(sample.dist_N,method="complete")
			plot(sample.clust_N)
			if(length(sample.dist_N)!=0){
				visible(g1_1)<-FALSE
				l$Nimblegen$Cluster_Plot<<-list()
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,400)
				visible(g1_1)<-TRUE
				}
				display()
  			}
		if(length(which(x=="Series_Matrix"))!=0){
			sample.dist_c1<-dist(t(data.matrixNorm.m)) 
			sample.dist_S<<-as.dist(1-cor(data.matrixNorm.m,method="pearson"))
			sample.clust_S<<-hclust(sample.dist_S,method="complete")
			plot(sample.clust_S)
			if(length(sample.dist_S)!=0){
				visible(g1_1)<-FALSE
				l$Series_Matrix$Cluster_Plot<<-list()
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,400)
				visible(g1_1)<-TRUE
				}
				display()
			}
		if(length(which(x=="Online_Data"))!=0){
			sample.dist_c1<-dist(t(data.matrix_onlineNorm.m)) 
			sample.dist_O<<-as.dist(1-cor(data.matrix_onlineNorm.m,method="pearson"))
			sample.clust_O<<-hclust(sample.dist_O,method="complete")
			plot(sample.clust_O)
			if(length(sample.dist_O)!=0){
				visible(g1_1)<-FALSE
				l$Online_Data$Cluster_Plot<<-list()
				tr<<-gtree(offspring=tree,container=g1_1)
				size(tr)<-c(300,400)
				visible(g1_1)<-TRUE
				}
				display()
			}
		dispose(w_dge)
		}else{
			gmessage("Plz select the data for Clustering","Select Data")
			}
			dispose(w_dge)
		},container=gp2_dge,anchor=c(1,-1))
	visible(w_dge)<-TRUE
	}
