filter_sp<-function(h,...){
	f<-function(h,...){
			x<<-svalue(h$obj)
		}
		try(({
		dat2Affy.m<-dat2Affy.m;datAgOne2.m<-datAgOne2.m;datAgTwo2.m<-datAgTwo2.m;datIllBA2.m2<-datIllBA2.m2;
		lumi_NQ.m<-lumi_NQ.m;data.matrix_Nimblegen2.m<-data.matrix_Nimblegen2.m;
		data.matrixNorm.m<-data.matrixNorm.m;data.matrix_onlineNorm.m<-data.matrix_onlineNorm.m;l<-l;tree<-tree;
			}),silent=TRUE)
		platforms=NULL;
		aa=0;bb=0;cc=0;dd=0;ee=0;ff=0;gg=0;hh=0;
		try(({
			if(exists("dat2Affy.m"))aa=length(dat2Affy.m)
			if(exists("datAgOne2.m"))bb=length(datAgOne2.m)
			if(exists("datAgTwo2.m"))cc=length(datAgTwo2.m)
			if(exists("datIllBA2.m2"))dd=length(datIllBA2.m2)
			if(exists("lumi_NQ.m"))ee=length(lumi_NQ.m)
			if(exists("data.matrix_Nimblegen2.m"))ff=length(data.matrix_Nimblegen2.m)
			if(exists("data.matrixNorm.m"))gg=length(data.matrixNorm.m)
			if(exists("data.matrix_onlineNorm.m"))hh=length(data.matrix_onlineNorm.m)
			}),silent=TRUE)
		if(aa!=0)platforms=c(platforms,"Affymetrix")
		if(bb!=0)platforms=c(platforms,"Agilent_OneColor")
		if(cc!=0)platforms=c(platforms,"Agilent_TwoColor")
		if(dd!=0)platforms=c(platforms,"Illumina_Beadarray")
		if(ee!=0)platforms=c(platforms,"Illumina_Lumi")
		if(ff!=0)platforms=c(platforms,"Nimblegen")
		if(gg!=0)platforms=c(platforms,"Series_Matrix")
		if(hh!=0)platforms=c(platforms,"Online_Data")
		print(platforms)

		use.dat2Affy.m=NULL;use.datAgOne2.m=NULL;use.datAgTwo2.m=NULL;use.datIllBA2.m2=NULL;use.lumi_NQ.m=NULL;
		use.data.matrix_Nimblegen2.m=NULL;use.data.matrixNorm.m=NULL;use.data.matrix_onlineNorm.m=NULL;
		dat2Affy.f=NULL;datAgOne2.f=NULL;datAgTwo2.f=NULL;datIllBA2.f=NULL;lumi_NQ.f=NULL;
		data.matrix_Nimblegen2.f=NULL;data.matrixNorm.f=NULL;data.matrix_onlineNorm.f=NULL;
		design_Affy=NULL;design_Ag1=NULL;design_Ag2=NULL;design_Il_B=NULL;design_Il_L=NULL;
		design_N=NULL;design_S=NULL;design_O=NULL;
		design2=NULL;design3=NULL;
		dgeF=NULL;
		dge2<-function(h2,...){
			design=NULL
			yy=NULL
			xf<-dim(h2)
			if(xf[2]%%3!=0 && xf[2]%%2!=0)h2<-h2[,-xf[2]]
			xf<-dim(h2)
			yf<-xf[2]/2
			groups<-c(rep("C",yf),rep("T",yf))
			groups<-as.factor(groups)
			dd<-try(design<-model.matrix(~groups),silent=TRUE)
			if(length(grep("Error",dd))!=0){
				gmessage("Wrong group comparisons. Plz try other group comparison","Error Comparison")
				}
			if(length(grep("Error",dd))==0){
				err<-try(fit<-lmFit(h2,design),silent=TRUE)
				if(length(grep("incompatible dimensions",err))!=0)gmessage("Incompatible dimensions or wrong group comparisons. Plz try other group comparisons","Error Comparison")
				yy<-try(toptable(fit,coef=2),silent=TRUE)
				if(length(grep("Error",yy))!=0)yy<-try(toptable(fit,coef=3),silent=TRUE)
				if(length(grep("Error",yy))!=0)yy<-try(toptable(fit,coef=4),silent=TRUE)
				if(length(grep("Error",yy))!=0){
					try(fit2<-eBayes(fit),silent=TRUE)
					}else{
					try(fit2<-eBayes(fit),silent=TRUE)
					}
				try(dgeF<<-fit2,silent=TRUE)
				try(design2<<-design,silent=TRUE)
				}
			}
		dge3<-function(h3,...){
			design=NULL
			yy=NULL
			xf=dim(h3)
			yf=xf[2]/3
			groups<-c(rep("C",yf),rep("T1",yf),rep("T2",yf))
			groups<-as.factor(groups)
			dd<-try(design<-model.matrix(~groups),silent=TRUE)
			if(length(grep("Error",dd))!=0){
			gmessage("Wrong group comparisons. Plz try other group comparison","Error Comparison")
			}
			if(length(grep("Error",dd))==0){
				err<-try(fit<-lmFit(h3,design),silent=TRUE)
				if(length(grep("incompatible dimensions",err))!=0)gmessage("Incompatible dimensions or wrong group comparisons. Plz try other group comparisons","Error Comparison")
				yy<-try(toptable(fit,coef=2),silent=TRUE)
				if(length(grep("Error",yy))!=0)yy<-try(toptable(fit,coef=3),silent=TRUE)
				if(length(grep("Error",yy))!=0)yy<-try(toptable(fit,coef=4),silent=TRUE)
				if(length(grep("Error in",yy))!=0){
					try(fit2<-eBayes(fit),silent=TRUE)
					}else{
					try(fit2<-eBayes(fit),silent=TRUE)
					}
				try(dgeF<<-fit2,silent=TRUE)
				try(design3<<-design,silent=TRUE)
				}
			}
		rm(use.dat2Affy.m,use.datAgOne2.m,use.datAgTwo2.m,use.datIllBA2.m2,use.lumi_NQ.m,
		use.data.matrix_Nimblegen2.m,use.data.matrixNorm.m,use.data.matrix_onlineNorm.m,
		dat2Affy.f,datAgOne2.f,datAgTwo2.f,datIllBA2.f,lumi_NQ.f,
		data.matrix_Nimblegen2.f,data.matrixNorm.f,data.matrix_onlineNorm.f,
		design_Affy,design_Ag1,design_Ag2,design_Il_B,design_Il_L,
		design_N,design_S,design_O,
		design2,design3,
		dgeF)
				
		x=NULL
		z=NULL
		sf_xx=NULL
		sf_methods<-c("Two_group_comparisons","Three_group_comparisons")
		sf_w<-gwindow("Select a Filter",width=300,height=150)
		sf_gp<-ggroup(container=sf_w,horizontal=FALSE)
		sf_x<-gtable(sf_methods,chosencol=1,container=sf_gp)
		size(sf_x)=c(200,100)
		sf_gp2<-ggroup(container=sf_gp,width=30,height=15,horizontal=TRUE)
		addHandlerClicked(sf_x,handler=function(h,...){
			sf_x2<-svalue(h$obj)
			sf_xx<<-sf_x2
			}
		)
		addSpring(sf_gp2)

		sf_y<-gbutton("CANCEL",border=TRUE,handler=function(h,...){
			dispose(sf_w)
			},container=sf_gp2,anchor=c(1,-1)
		)
		sf_y2<-gbutton("OK",border=TRUE,handler=function(h,...){
			dispose(sf_w)
			svalue(sb)<-"Working... Plz wait..."
			Sys.sleep(1)

			if(sf_xx=="Two_group_comparisons")
			{
				w_f<-gwindow("Select your data",width=260,height=280,visible=FALSE)
				gp_f<-ggroup(container=w_f,horizontal=FALSE)
				size(gp_f)=c(220,180)
				cbg<-gcheckboxgroup(platforms,container=gp_f,handler=f)
				svalue(cbg,index=FALSE)<-1:8
				gp2_f<-ggroup(container=gp_f,width=30,height=15,horizontal=TRUE)
				addSpring(gp2_f)
				y<-gbutton("CANCEL",border=TRUE,handler=function(h,...){
					dispose(w_f)
					},container=gp2_f,anchor=c(1,-1))
				y2<-gbutton("OK",border=TRUE,handler=function(h,...){
					if(length(x)!=0){
						dispose(w_f)
						if(length(which(x=="Affymetrix"))!=0){
							use.dat2Affy.m<<-dat2Affy.m
							xxf=dim(use.dat2Affy.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.dat2Affy.m<<-use.dat2Affy.m[,-xxf[2]]
							dge2(use.dat2Affy.m)
							dat2Affy.f<<-dgeF
							dgeF=NULL
							design_Affy<<-design2
							degign2=NULL
							if(length(dat2Affy.f)!=0){
								visible(g1_1)<-FALSE
								l$Affymetrix$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(dat2Affy.f)
								}
							display()
							}							
						if(length(which(x=="Agilent_OneColor"))!=0){
							use.datAgOne2.m<<-datAgOne2.m
							xxf=dim(use.datAgOne2.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.datAgOne2.m<<-use.datAgOne2.m[,-xxf[2]]
							dge2(use.datAgOne2.m)
							datAgOne2.f<<-dgeF
							dgeF=NULL
							design_Ag1<<-design2
							design2=NULL
							if(length(datAgOne2.f)!=0){
								visible(g1_1)<-FALSE
								l$Agilent_OneColor$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(datAgOne2.f)
								}
							display()
							}
						if(length(which(x=="Agilent_TwoColor"))!=0){
							use.datAgTwo2.m<<-datAgTwo2.m
							xxf=dim(use.datAgTwo2.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.datAgTwo2.m<<-use.datAgTwo2.m[,-xxf[2]]
							dge2(use.datAgTwo2.m)
							datAgTwo2.f<<-dgeF
							dgeF=NULL
							design_Ag2<<-design2
							design2=NULL
							if(length(datAgTwo2.f)!=0){
								visible(g1_1)<-FALSE
								l$Agilent_TwoColor$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(datAgTwo2.f)
								}
							display()
							}
						if(length(which(x=="Illumina_Beadarray"))!=0){
							use.datIllBA2.m2<<-datIllBA2.m2
							xxf=dim(use.datIllBA2.m2)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.datIllBA2.m2<<-use.datIllBA2.m2[,-xxf[2]]
							dge2(use.datIllBA2.m2)
							datIllBA2.f<<-dgeF
							dgeF=NULL
							design_Il_B<<-design2
							design2=NULL
							if(length(datIllBA2.f)!=0){
								visible(g1_1)<-FALSE
								l$Illumina_Beadarray$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(datIllBA2.f)
								}
							display()
							}
						if(length(which(x=="Illumina_Lumi"))!=0){
							use.lumi_NQ.m<<-lumi_NQ.m
							xxf=dim(use.lumi_NQ.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.lumi_NQ.m<<-use.lumi_NQ.m[,-xxf[2]]
							dge2(use.lumi_NQ.m)
							lumi_NQ.f<<-dgeF
							dgeF=NULL
							design_Il_L<<-design2
							design2=NULL
							if(length(lumi_NQ.f)!=0){
								visible(g1_1)<-FALSE
								l$Illumina_Lumi$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(lumi_NQ.f)
								}							
							display()
							}
						if(length(which(x=="Nimblegen"))!=0){
							use.data.matrix_Nimblegen2.m<<-data.matrix_Nimblegen2.m
							xxf=dim(use.data.matrix_Nimblegen2.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.data.matrix_Nimblegen2.m<<-use.data.matrix_Nimblegen2.m[,-xxf[2]]
							dge2(use.data.matrix_Nimblegen2.m)
							data.matrix_Nimblegen2.f<<-dgeF
							dgeF=NULL
							design_N<<-design2
							design2=NULL
							if(length(data.matrix_Nimblegen2.f)!=0){
								visible(g1_1)<-FALSE
								l$Nimblegen$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(data.matrix_Nimblegen2.f)
								}							
							display()
							}
						if(length(which(x=="Series_Matrix"))!=0){
							use.data.matrixNorm.m<<-data.matrixNorm.m
							xxf=dim(use.data.matrixNorm.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.data.matrixNorm.m<<-use.data.matrixNorm.m[,-xxf[2]]
							dge2(use.data.matrixNorm.m)
							data.matrixNorm.f<<-dgeF
							dgeF=NULL
							design_S<<-design2
							design2=NULL
							if(length(data.matrixNorm.f)!=0){
								visible(g1_1)<-FALSE
								l$Series_Matrix$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(data.matrixNorm.f)
								}		
							display()
							}
						if(length(which(x=="Online_Data"))!=0){
							use.data.matrix_onlineNorm.m<<-data.matrix_onlineNorm.m
							xxf=dim(use.data.matrix_onlineNorm.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.data.matrix_onlineNorm.m<<-use.data.matrix_onlineNorm.m[,-xxf[2]]
							dge2(use.data.matrix_onlineNorm.m)
							data.matrix_onlineNorm.f<<-dgeF
							dgeF=NULL
							design_O<<-design2
							design2=NULL
							if(length(data.matrix_onlineNorm.f)!=0){
								visible(g1_1)<-FALSE
								l$Online_Data$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(data.matrix_onlineNorm.f)
								}		
							display()
							}
						dispose(w_f)
						}else{
						gmessage("Plz select the data for filtering","Select Data")
						}
					},container=gp2_f,anchor=c(1,-1))
				visible(w_f)<-TRUE
				}
			else if(sf_xx=="Three_group_comparisons")
			{
				w_f<-gwindow("Select your data",width=260,height=280,visible=FALSE)
				gp_f<-ggroup(container=w_f,horizontal=FALSE)
				size(gp_f)=c(220,180)
				cbg<-gcheckboxgroup(platforms,container=gp_f,handler=f)
				svalue(cbg,index=FALSE)<-1:8
				gp2_f<-ggroup(container=gp_f,width=30,height=15,horizontal=TRUE)
				addSpring(gp2_f)
				y<-gbutton("CANCEL",border=TRUE,handler=function(h,...){
					dispose(w_f)
					},container=gp2_f,anchor=c(1,-1))
				y2<-gbutton("OK",border=TRUE,handler=function(h,...){
					if(length(x)!=0){
						dispose(w_f)
						if(length(which(x=="Affymetrix"))!=0){
							use.dat2Affy.m<<-dat2Affy.m
							xxf=dim(use.dat2Affy.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.dat2Affy.m<<-use.dat2Affy.m[,-xxf[2]]
							dge3(use.dat2Affy.m)
							dat2Affy.f<<-dgeF
							dgeF=NULL
							design_Affy<<-design3
							design3=NULL
							if(length(dat2Affy.f)!=0){
								visible(g1_1)<-FALSE
								l$Affymetrix$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(dat2Affy.f)
								}		
							display()
							}
						if(length(which(x=="Agilent_OneColor"))!=0){
							use.datAgOne2.m<<-datAgOne2.m
							xxf=dim(use.datAgOne2.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.datAgOne2.m<<-use.datAgOne2.m[,-xxf[2]]
							dge3(use.datAgOne2.m)
							datAgOne2.f<<-dgeF
							dgeF=NULL
							design_Ag1<<-design3
							design3=NULL
							if(length(datAgOne2.f)!=0){
								visible(g1_1)<-FALSE
								l$Agilent_OneColor$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(datAgOne2.f)
								}		
							display()
							}
						if(length(which(x=="Agilent_TwoColor"))!=0){
							use.datAgTwo2.m<<-datAgTwo2.m
							xxf=dim(use.datAgTwo2.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.datAgTwo2.m<<-use.datAgTwo2.m[,-xxf[2]]
							dge3(use.datAgTwo2.m)
							datAgTwo2.f<<-dgeF
							design_Ag2<<-design3
							design3=NULL
							if(length(datAgTwo2.f)!=0){
								visible(g1_1)<-FALSE
								l$Agilent_TwoColor$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(datAgTwo2.f)
								}		
							display()
							}
						if(length(which(x=="Illumina_Beadarray"))!=0){
							use.datIllBA2.m2<<-datIllBA2.m2
							xxf=dim(use.datIllBA2.m2)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.datIllBA2.m2<<-use.datIllBA2.m2[,-xxf[2]]
							dge3(use.datIllBA2.m2)
							datIllBA2.f<<-dgeF
							dgeF=NULL
							design_Il_B<<-design3
							design3=NULL
							if(length(datIllBA2.f)!=0){
								visible(g1_1)<-FALSE
								l$Illumina_Beadarray$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(datIllBA2.f)
								}		
							display()
							}
						if(length(which(x=="Illumina_Lumi"))!=0){
							use.lumi_NQ.m<<-lumi_NQ.m
							xxf=dim(use.lumi_NQ.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.lumi_NQ.m<<-use.lumi_NQ.m[,-xxf[2]]
							dge3(use.lumi_NQ.m)
							lumi_NQ.f<<-dgeF
							dgeF=NULL
							design_Il_L<<-design3
							design3=NULL
							if(length(lumi_NQ.f)!=0){
								visible(g1_1)<-FALSE
								l$Illumina_Lumi$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(lumi_NQ.f)
								}		
							display()
							}
						if(length(which(x=="Nimblegen"))!=0){
							use.data.matrix_Nimblegen2.m<<-data.matrix_Nimblegen2.m
							xxf=dim(use.data.matrix_Nimblegen2.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.data.matrix_Nimblegen2.m<<-use.data.matrix_Nimblegen2.m[,-xxf[2]]
							dge3(use.data.matrix_Nimblegen2.m)
							data.matrix_Nimblegen2.f<<-dgeF
							dgeF=NULL
							design_N<<-design3
							design3=NULL
							if(length(data.matrix_Nimblegen2.f)!=0){
								visible(g1_1)<-FALSE
								l$Nimblegen$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(data.matrix_Nimblegen2.f)
								}		
							display()
							}
						if(length(which(x=="Series_Matrix"))!=0){
							use.data.matrixNorm.m<<-data.matrixNorm.m
							xxf=dim(use.data.matrixNorm.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.data.matrixNorm.m<<-use.data.matrixNorm.m[,-xxf[2]]
							dge3(use.data.matrixNorm.m)
							data.matrixNorm.f<<-dgeF
							dgeF=NULL
							design_S<<-design3
							design3=NULL
							if(length(data.matrixNorm.f)!=0){
								visible(g1_1)<-FALSE
								l$Series_Matrix$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(data.matrixNorm.f)
								}		
							display()	
							}
						if(length(which(x=="Online_Data"))!=0){
							use.data.matrix_onlineNorm.m<<-data.matrix_onlineNorm.m
							xxf=dim(use.data.matrix_onlineNorm.m)
							if(xxf[2]%%3!=0 && xxf[2]%%2!=0)use.data.matrix_onlineNorm.m<<-use.data.matrix_onlineNorm.m[,-xxf[2]]
							dge3(use.data.matrix_onlineNorm.m)
							data.matrix_onlineNorm.f<<-dgeF
							dgeF=NULL
							design_O<<-design3
							design3=NULL
								if(length(data.matrix_onlineNorm.f)!=0){
								visible(g1_1)<-FALSE
								l$Online_Data$Filtered<<-list()
								tr<<-gtree(offspring=tree,container=g1_1)
								size(tr)<-c(300,400)
								visible(g1_1)<-TRUE
								stat_sign(data.matrix_onlineNorm.f)
								}		
							display()	
							}
						dispose(w_f)
						
						}else{
						gmessage("Plz select the data for filtering","Select Data")
						}
					},container=gp2_f,anchor=c(1,-1))
				visible(w_f)<-TRUE
				}
			svalue(sb)<-"Done"
		},container=sf_gp2,anchor=c(1,-1)
	)
}	
