# define generics for methods we are going to define
setGeneric("seriesLength", function(x) standardGeneric("seriesLength") )
setGeneric("rowIds", function(x) standardGeneric("rowIds") )
setGeneric("numRows", function(x) standardGeneric("numRows") )
setGeneric("colIds", function(x) standardGeneric("colIds") )
setGeneric("numCols", function(x) standardGeneric("numCols") )
setGeneric("rowIds<-", function(x, value) standardGeneric("rowIds<-") )
setGeneric("colIds<-", function(x, value) standardGeneric("colIds<-") )
setGeneric("numRows<-", function(x, value) standardGeneric("numRows<-") )
setGeneric("ncol<-", function(x, value) standardGeneric("ncol<-") )
setGeneric("nrow<-", function(x, value) standardGeneric("nrow<-") )
setGeneric("numCols<-", function(x, value) standardGeneric("numCols<-") )
setGeneric("subscript2d", function(x, i, j) standardGeneric("subscript2d") )
setGeneric("subscript2d<-", function(x, i, j, value) standardGeneric("subscript2d<-") )
setGeneric("shift", function(x, k = 1) standardGeneric("shift") )
setGeneric("seriesLag", function(X, k=1, trim=FALSE, pad=NA) standardGeneric("seriesLag"))

setGeneric("aggregate", function(x, ...) standardGeneric("aggregate"))
setGeneric("deltat", function(x, ...) standardGeneric("deltat"))
setGeneric("end", function(x, ...) standardGeneric("end"))
setGeneric("frequency", function(x, ...) standardGeneric("frequency"))
setGeneric("ncol", function(x) standardGeneric("ncol"))
setGeneric("nrow", function(x) standardGeneric("nrow"))
setGeneric("row.names", function(x) standardGeneric("row.names"))
setGeneric("row.names<-", function(x, value) standardGeneric("row.names<-"))
setGeneric("start", function(x, ...) standardGeneric("start"))
setGeneric("units", function(x) standardGeneric("units"))
setGeneric("window", function(x, ...) standardGeneric("window"))


