print.steeptest<- function(x,...)
{
  options(digits = max(4,getOption("digits") - 4),scipen=999)
  cat("    ","\n")
  if (x$method == "Dij"){
    cat("RESULTS OF STEEPNESS ANALYSIS OF THE MATRIX OF DYADIC DOMINANCES CORRECTED FOR CHANCE","\n")
    cat("=====================================================================================","\n")}
  if (x$method == "Pij"){
    cat("RESULTS OF STEEPNESS ANALYSIS OF THE MATRIX OF WIN PROPORTIONS","\n")    
    cat("==============================================================","\n")}
  cat("    ","\n")
  cat("    ","\n")
  if (x$method == "Dij")
    cat("Dij","\n")
  if (x$method == "Pij")
    cat("Pij","\n")    
  cat("===","\n")
  cat("    ","\n")
  print(x$matdom)
  cat("    ","\n")
  cat("    ","\n")
  cat("DAVID'S SCORES","\n")
  cat("==============","\n")
  cat("    ","\n")
  print(x$DS)
  cat("    ","\n")
  cat("    ","\n")
  cat("NORMALIZED DAVID'S SCORES","\n")
  cat("=========================","\n")
  cat("    ","\n")
  print(x$NormDS)
  cat("    ","\n")
  cat("    ","\n")
  cat("STEEPNESS","\n")
  cat("=========","\n")
  cat("    ","\n")
  cat("Slope (absolute) = ",x$Stp,"\n")
  cat("    ","\n")
  cat("    ","\n")
  cat("INTERCEPT","\n")
  cat("=========","\n")
  cat("    ","\n")
  cat("Intercept = ",x$interc,"\n")
  cat("    ","\n")
  invisible(x)
}