library(nws)
library(grid)
options(device='X11')
grid.newpage()
ws <- netWorkSpace(Sys.getenv('PF_WORKSPACE'))
nwsStore(ws, 'seq', 'ready')
ignore <- nwsFind(ws, 'go')
source('sportfolio.R')
ignore <- grid.locator()
