# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_generic <- function(st, data, query, k, eps) {
    .Call('nabor_knn_generic', PACKAGE = 'nabor', st, data, query, k, eps)
}

