`setXMCOL` <-
function()
{
  XMCOL<-c("black",
            "white",
            "red",
            "light blue",
            "mediumpurple",
            "azure",
            "darkorange",
            "green",
            "plum",
            "LemonChiffon1",
            "SeaGreen1",
            "DeepSkyBlue1",
            "turquoise1",
            "DeepPink",
            "gold",
            "lightcyan",
            "OldLace",
            "DarkSlateGray",
            "DarkSeaGreen",
            "GreenYellow",
            "orange",
            "RoyalBlue",
            "SkyBlue1",
            "cyan1",
            "DarkSlateGray4",
            "dimgray",
            "beige",
            "aquamarine1",
            "LemonChiffon",
            "AntiqueWhite",
            "MintCream",
            "lavender",
            "PeachPuff1",
            "cornsilk2",
            "LightSkyBlue1",
            "MediumAquamarine",
            "PaleGreen",
            "LightSeaGreen",
            "PaleGreen3",
            "SkyBlue",
            "green",
            "LightCyan2",
            "yellow1",
            "IndianRed",
            "salmon",
            "bisque3",
            "yellow2",
            "khaki",
            "moccasin",
            "pink",
            "SteelBlue2",
            "MistyRose2",
            "tan4",
            "SeaGreen1",
            "DeepPink",
            "magenta3",
            "LightPink",
            "thistle1",
            "LightSalmon",
            "sienna4")

  return(XMCOL)

  

}

