print.sla <-
function(x, ...)
{
	cat('\nCall:  ')
	print(x$Call)
	cat('\nCoefficients for Models A, B, C and D:\n\n')
	cat('Model A:\n')
	coef.A <- coef(x$Mod.A)
	names(coef.A) <- c('Int_1', 'Slo_1', 'Int_2', 'Slo_2')
	print(coef.A)
	cat('\n')
	cat('Model B:\n')
	coef.B <- coef(x$Mod.B)
	names(coef.B) <- c('Com_Int', 'Com_Slo')
	print(coef.B)
	cat('\n')
	cat('Model C:\n')
	coef.C <- coef(x$Mod.C)
	names(coef.C) <- c('Int_1', 'Int_2', 'Com_Slo')
	print(coef.C)
	cat('\n')
	cat('Model D:\n')
	coef.D <- coef(x$Mod.D)
	names(coef.D) <- c('Com_Int', 'Slo_1', 'Slo_2')
	print(coef.D)
}
