if (getRversion() >= '2.15.1')
  globalVariables(c('top', 'buttonsFrame',
                    'lmatrowsVariable', 'choose.lmat.rowsFrame', 'right.omd', 'x.offset',
                    'ry', 'tieVariable', 'tieFrame', 'predictVariable', 'seVariable',
                    'predictFrame', 'seFrame', 'ShapWilkVariable', 'normFrame',
                    'starsVariable', 'starsFrame', 'jitterXVariable', 'subsetVariable',
                    'points.yhatVariable', 'modelVariable', 'residualsVariable',
                    'subsetFrame', 'optionsFrame', 'modelFrame', 'residualsFrame',
                    '.groups', '.linesByGroup', 'rgl.bringtotop', 'groupsFrame',
                    'auto.keyVariable', 'outerVariable', 'x.relationVariable',
                    'y.relationVariable', 'pointsVariable', 'linesVariable', 'typeFrame',
                    'x.relationFrame', 'y.relationFrame', 'rowPercentsVariable',
                    'colPercentsVariable', 'totPercentsVariable', 'chisqTestVariable',
                    'chisqCompVariable', 'chiCompVariable', 'expFreqVariable',
                    'fisherTestVariable', '.Test', '.Table', 'percentsFrame', 'testsFrame',
                    'statisticVariable', 'statisticFrame', 'helpButton', 'hypothVariable',
                    'hypothFrame', 'rgl.clear', 'rgl.viewpoint', 'rgl.bg', 'rgl.spheres',
                    'rgl.points', 'rgl.lines', 'rgl.texts', 'rgl.surface', 'rgl.quads',
                    'jitterYVariable', 'logXVariable', 'logYVariable', 'identifyVariable',
                    'boxplotsVariable', 'lsLineVariable', 'smoothLineVariable',
                    'spreadVariable', 'scatterPlot', 'diagonalVariable',
                    'diagonalDirectionVariable', 'diagonalFrame',
                    'diagonalDirectionFrame', 'horizontalVariable',
                    'as.percentVariable', 'positive.orderVariable',
                    'chisqComponentsVariable',
                    'x.logVariable', 'y.logVariable', 'x.logFrame', 'y.logFrame', 'horizontalFrame',
                    'boxWidthUnitValue','ReferenceZeroValue', 'BrewerPaletteName', 'xlabName',
                    'ylabName', 'subName',
                    'reverseVariable',  'stripVariable', 'strip.leftVariable', 'rowsortVariable',
                    'useOuterStripsVariable', 'combineLimitsVariable',
                    'relationxVariable', 'relationyVariable'
                    ))

# if (getRversion() >= '2.15.1')
#   globalVariables(add=TRUE,
#                   c('.Tcl', 'tcl', 'tclRequire', 'tclServiceMode', 'tclvalue<-',
#                     'tclVar', 'tkbind', 'tkcget', 'tkcheckbutton', 'tkconfigure',
#                     'tkchooseDirectory', 'tkcurselection', 'tkdelete',
#                     'tkdestroy', 'tkentry',
#                     'tkframe', 'tkgrab.release', 'tkgrab.set',
#                     'tkgetOpenFile', 'tkgetSaveFile',
#                     'tkgrid', 'tkgrid.columnconfigure', 'tkgrid.configure',
#                     'tkgrid.rowconfigure',
#                     'tkicursor', 'tkindex', 'tkinsert',
#                     'tkinvoke', 'tkitemconfigure', 'tklabel', 'tklistbox', 'tkmark.set',
#                     'tkmessageBox', 'tkpack', 'tkradiobutton', 'tkraise', 'tkscale',
#                     'tkscrollbar', 'tk_select.list', 'tkselection.clear',
#                     'tkselection.set', 'tkset', 'tktag.configure', 'tktext', 'tktoplevel',
#                     'tkwait.window', 'tkwm.deiconify', 'tkwm.iconbitmap',
#                     'tkwm.geometry', 'tkwm.protocol',
#                     'tkwm.resizable', 'tkwm.title', 'tkwm.transient',
#                     'tkxview.moveto', 'tkxview', 'tkyview'))
#
