odds <- 1 + 2*(0:4);
primes <- c(2,3,5,7,11,13);
length(odds);
length(primes);
odds + 1;
odds + primes;
odds * primes;
odds > 5;
sum(odds > 5);
sum(primes < 5 | primes > 9);
odds[3];
odds[-3];
primes[odds];
primes[primes >=7];
sum(primes[primes > 5]);
sum(odds[odds > 5]);
