{
  RSMI <- c('CCCCCC=CCC=CCC=CCC=CCCCC(=O)[O-].CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CCCCCC=CCC=CCC=CCC=CCCCC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].CCC(=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CCC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'C(=O)([O-])C=CC1(=CC=C(O)C=C1).CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(=O)C=CC1(C=CC(O)=CC=1))COP(=O)(OP(=O)(OCC2(C(OP([O-])(=O)[O-])C(O)C(O2)N4(C3(=C(C(N)=NC=N3)N=C4))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'C([O-])(=O)C=CC1(C=C(O)C(O)=CC=1).CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(=O)C=CC1(=CC=C(O)C(=C1)O))COP(=O)(OP(=O)(OCC2(C(OP([O-])(=O)[O-])C(O)C(O2)N4(C3(=C(C(N)=NC=N3)N=C4))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'COC1(C=C(C=C(OC)C(O)=1)C=CC([O-])=O).CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(=O)C=CC1(C=C(OC)C(O)=C(OC)C=1))COP(=O)(OP(=O)(OCC2(C(OP([O-])(=O)[O-])C(O)C(O2)N4(C3(=C(C(N)=NC=N3)N=C4))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'CC12(CCC(=O)C(CCC(=O)[O-])[CH](CCC(=O)1)2).C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(=O)CCC1(C(=O)CCC2(C)(C(=O)CC[CH]12)))COP(=O)(OP(=O)(OCC3(C(OP([O-])(=O)[O-])C(O)C(O3)N5(C4(=C(C(N)=NC=N4)N=C5))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'C(C1(C=CC=CC=1))([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(=O)C1(C=CC=CC=1))COP(=O)(OP(=O)(OCC2(C(OP([O-])(=O)[O-])C(O)C(O2)N4(C3(=C(C(N)=NC=N3)N=C4))))[O-])[O-].O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(CCCC(C)C(=O)[O-])[CH]2(CC[CH]1([CH]3(C(O)C[CH]4(CC(O)CCC(C)([CH](CCC(C)12)3)4)))).CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-].CC(C4(CCC3(C2(C(CC1(CC(CCC1(C2CCC34C)C)O))O))))CCCC(C(SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC5(C(OP([O-])(=O)[O-])C(O)C(O5)N7(C6(=C(C(N)=NC=N6)N=C7))))[O-])[O-])=O)C',
            'CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].CC(C)CCCC(C)CCCC(C)CCCC(C)CC(=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)CCCC(C)CCCC(C)CCCC(C)CC(SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-])=O.O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'C(CO)C([O-])=O.C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(CCO)=O)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'C([O-])(=O)C1(=CC(O)=CC=C1).CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)(C(O)C(NCCC(=O)NCCSC(C1(C=C(C=CC=1)O))=O)=O)COP(OP(OCC2(C(OP([O-])(=O)[O-])C(C(O2)N3(C=NC4(=C3N=CN=C(N)4)))O))(=O)[O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'COC1(=CC(C=CC([O-])=O)=CC=C(O)1).C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(=O)C=CC1(C=C(OC)C(O)=CC=1))COP(=O)(OP(=O)(OCC2(C(OP([O-])(=O)[O-])C(O)C(O2)N4(C3(=C(C(N)=NC=N3)N=C4))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'C(C1(C(=CC=CC=1)N))(=O)[O-].CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(=O)C1(=CC=CC=C(N)1))COP(=O)(OP(=O)(OCC2(C(OP([O-])(=O)[O-])C(O)C(O2)N4(C3(=C(C(N)=NC=N3)N=C4))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CCC=CCC=CCC=CCCCCCCCC(=O)[O-].CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CCC=CCC=CCC=CCCCCCCCC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)([O-])OP(=O)([O-])OCC3(OC(N2(C=NC1(C(N)=NC=NC=12)))C(O)C(OP(=O)([O-])[O-])3).O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'CCCCCCCC(=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CCCCCCCC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'CCCCCCCCC=CCCCCCCCCCCCCCC(=O)[O-].CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CCCCCCCCC=CCCCCCCCCCCCCCC(SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-])=O.O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'CCC=CCC=CCC=CCC=CCC=CCCCC(=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CCC=CCC=CCC=CCC=CCC=CCCCC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'CCCCCCCCCCCCCCCC([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CCCCCCCCCCCCCCCC(SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-])=O.O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'CCCCCCCCC=CCCCCCCCC([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CCCCCCCCC=CCCCCCCCC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'CCCCCC=CCC=CCCCCCCCC([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CCCCCC=CCC=CCCCCCCCC(SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-])=O.O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'CC(C)CCCC(C)CCCC(C)CCCC(C)=CC(=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CC(C)CCCC(C)CCCC(C)CCCC(C)=CC(SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-])=O.C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'CC(CCCC(CCCC(C)CCCC(C([O-])=O)C)C)C.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)CCCC(C)CCCC(C)CCCC(C)C(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].CC([O-])=O.C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].O=P(O)(OP([O-])([O-])=O)[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O',
            'CC(CCCC(C)C(=O)[O-])[CH]2(CC[CH]1([CH]3(C(O)C[CH]4(CC(O)CCC(C)([CH](CC(O)C(C)12)3)4)))).C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CC(C4(CCC3(C2(C(CC1(CC(CCC1(C2CC(O)C34C)C)O))O))))CCCC(C(SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC5(C(OP([O-])(=O)[O-])C(O)C(O5)N7(C6(=C(C(N)=NC=N6)N=C7))))[O-])[O-])=O)C.C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC([CH]3(CC[CH]4([CH]2(C(O)C[CH]1(CC(O)CCC(C)1[CH]2CC(O)C(C)34)))))CCC(=O)[O-].CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-].CC(CCC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-])[CH]5(CC[CH]6([CH]7(C(O)C[CH]4(CC(O)CCC(C)4[CH](CC(O)C(C)56)7))))',
            'CC(CCCC(C)C(=O)[O-])C2(CC[CH]3([CH]4(CCC1(=CC(=O)CCC(C)1[CH](CCC(C)23)4)))).C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O.CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-]>>CC(CCCC(C)C(SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(OP(=O)(OCC1(C(OP([O-])(=O)[O-])C(O)C(O1)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-])=O)[CH]5(CC[CH]6([CH]7(CCC4(=CC(=O)CCC(C)4[CH](CCC(C)56)7)))).C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]',
            'C(=O)([O-])C=CC1(=CC=CC=C1).CC(C)(C(O)C(=O)NCCC(=O)NCCS)COP(=O)(OP(=O)(OCC1(OC(C(C1OP([O-])(=O)[O-])O)N3(C2(=C(C(N)=NC=N2)N=C3))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP(OP(=O)([O-])OP(=O)([O-])[O-])([O-])=O>>CC(C)(C(O)C(=O)NCCC(=O)NCCSC(=O)C=CC1(=CC=CC=C1))COP(=O)(OP(=O)(OCC2(C(OP([O-])(=O)[O-])C(O)C(O2)N4(C3(=C(C(N)=NC=N3)N=C4))))[O-])[O-].C(C3(C(C(C(N2(C1(=C(C(=NC=N1)N)N=C2)))O3)O)O))OP([O-])([O-])=O.O=P(O)(OP([O-])([O-])=O)[O-]')
  EC <- c('6.2.1.15', '6.2.1.17', '6.2.1.12', '6.2.1.12', '6.2.1.12', '6.2.1.41', '6.2.1.25', '6.2.1.28', '6.2.1.24', '6.2.1.36', '6.2.1.37', '6.2.1.34', '6.2.1.32', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.1', '6.2.1.7', '6.2.1.7', '6.2.1.f', '6.2.1')
  
  message('Defined a Reaction list.')
  message(paste('Size:', length(RSMI)))
}

readline("\nType  <Return>\t to start : ")
{
  message('Computing reaction similarity matrix: ')
  simMat <- rs.compute.sim.matrix(RSMI)
  rownames(simMat) <- EC
  colnames(simMat) <- EC
}

readline("\nType  <Return>\t to start : ")
{
  message('Clustering reaction based on similarities: ')
  d <- dist(simMat)
  hc <- hclust(d)
  plot(hc)
}