data(fremantle)
fm.gev <- gev.fit(fremantle[,2])
gev.diag(fm.gev)
gev.profxi(fm.gev, -0.5, 0.1)
gev.prof(fm.gev, 100, 1.8, 2.2)
covar <- cbind((fremantle[,1] - 1943)/46, fremantle[,3])
gev.fit(fremantle[,2], ydat = covar, mul = 1)
gev.fit(fremantle[,2], ydat = covar, mul = 1, sigl = 1, siglink = exp)
fm.gev2 <- gev.fit(fremantle[,2], ydat = covar, mul = c(1,2))
gev.diag(fm.gev2)
