data(danish)
qplot(danish)
meplot(danish)
emplot(danish, alog="xy")
records(danish)
hill(danish)

out <- gpd(danish, 10)
plot(out)
tp <- tailplot(out)
gpd.q(tp, 0.999)
gpd.q(tp, 0.999, "wald")
shape(danish)
quant(danish, 0.999)
riskmeasures(out, c(0.999, 0.9999))
