# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

JacobiCpp <- function(x, only_values = FALSE, eps = 0.0) {
    .Call('JacobiEigen_JacobiCpp', PACKAGE = 'JacobiEigen', x, only_values, eps)
}

