setGeneric("summary", function(object) standardGeneric("summary"))
setGeneric("PretrainLearningRate", function(object) standardGeneric("PretrainLearningRate"))
setGeneric("LearningRate", function(object) standardGeneric("LearningRate"))
setGeneric("CorruptionLevel", function(object) standardGeneric("CorruptionLevel"))
setGeneric("TrainingEpochs", function(object) standardGeneric("TrainingEpochs"))
setGeneric("HiddenRepresentation", function(object) standardGeneric("HiddenRepresentation"))
setGeneric("PretrainingEpochs", function(object) standardGeneric("PretrainingEpochs"))
setGeneric("FinetuneLearningRate", function(object) standardGeneric("FinetuneLearningRate"))
setGeneric("Step", function(object) standardGeneric("Step"))
setGeneric("FinetuneEpochs", function(object) standardGeneric("FinetuneEpochs"))
setGeneric("pretrain", function(object) standardGeneric("pretrain"))
setGeneric("train", function(object) standardGeneric("train"))
setGeneric("finetune", function(object) standardGeneric("finetune"))
setGeneric("predict", function(object, test) standardGeneric("predict"))
setGeneric("reconstruct", function(object, test) standardGeneric("reconstruct"))
setGeneric("setPretrainLearningRate", function(object, x) standardGeneric("setPretrainLearningRate"))
setGeneric("setStep", function(object, x) standardGeneric("setStep"))
setGeneric("setPretrainEpochs", function(object, x) standardGeneric("setPretrainEpochs"))
setGeneric("setFinetuneEpochs", function(object, x) standardGeneric("setFinetuneEpochs"))
setGeneric("setFinetuneLearningRate", function(object, x) standardGeneric("setFinetuneLearningRate"))
setGeneric("setLearningRate", function(object, x) standardGeneric("setLearningRate"))
setGeneric("setCorruptionLevel", function(object, x) standardGeneric("setCorruptionLevel"))
setGeneric("setTrainingEpochs", function(object, x) standardGeneric("setTrainingEpochs"))
setGeneric("setHiddenRepresentation", function(object, x) standardGeneric("setHiddenRepresentation"))

