# define generics for methods we are going to define
# setGeneric("summary", function(object, ...) standardGeneric("summary"))
# setGeneric("unique", function(x, incomparables = FALSE, ...) standardGeneric("unique"))
# setGeneric("duplicated", function(x, incomparables = FALSE, ...) standardGeneric("duplicated"))
# setGeneric("all.equal.list", function(target, current, check.attributes = TRUE, ...) standardGeneric("all.equal.list"))
# setGeneric("format", function(x, ...) standardGeneric("format"))
# setGeneric("logb", function(x, base = exp(1)) standardGeneric("logb"))
# setGeneric("match", function(x, table, nomatch = NA_integer_, incomparables = NULL) standardGeneric("match"))
# setGeneric("mean", function(x, ...) standardGeneric("mean"))
# setGeneric("median", function(x, na.rm = FALSE) standardGeneric("median"))
# setGeneric("quantile", function(x, ...) standardGeneric("quantile"))
# setGeneric("sort", function(x, decreasing = FALSE, ...) standardGeneric("sort"))
# setGeneric("sort.list", function(x, partial = NULL, na.last = TRUE, decreasing = FALSE, method = c("shell", "quick", "radix")) standardGeneric("sort.list"))
# setGeneric("cor", function(x, y = NULL, use = "everything", method = c("pearson", "kendall", "spearman")) standardGeneric("cor"))
# setGeneric("var", function(x, y = NULL, na.rm = FALSE, use) standardGeneric("var"))
# setGeneric("cut", function(x, ...) standardGeneric("cut"))

# if (version$language == "R") {
# setGeneric("diff", function(x, lag = 1L, differences = 1L, ...) base:::diff(x, lag, differences, ...))
# } else {
# setGeneric("diff", function(x, lag = 1L, differences = 1L, ...) standardGeneric("diff"))
# }

setGeneric("sort.list", signature="x")
setGeneric("days" , function(x) standardGeneric("days"))
setGeneric("years" , function(x) standardGeneric("years"))
setGeneric("hours" , function(x) standardGeneric("hours"))
setGeneric("minutes" , function(x) standardGeneric("minutes"))
setGeneric("seconds" , function(x) standardGeneric("seconds"))
setGeneric("yeardays", function(x) standardGeneric("yeardays"))
setGeneric("mdy", function(x) standardGeneric("mdy"))
setGeneric("hms", function(x) standardGeneric("hms"))
setGeneric("wdydy", function(x) standardGeneric("wdydy"))
setGeneric("timeConvert", function(x, to.zone, from.zone) standardGeneric("timeConvert"))
setGeneric("weekdays", function(x, abbreviate=TRUE) standardGeneric("weekdays"))
setGeneric("months", function(x, abbreviate=TRUE) standardGeneric("months"))
setGeneric("quarters", function(x, abbreviate=TRUE) standardGeneric("quarters"))
setGeneric("timeFloor", function(x) standardGeneric("timeFloor"))
setGeneric("timeCeiling", function(x) standardGeneric("timeCeiling"))
setGeneric("timeTrunc", function(x) standardGeneric("timeTrunc"))
# setGeneric("rev", function(x) standardGeneric("rev"))
setGeneric("shiftPositions", function(x, k = 1) standardGeneric("shiftPositions") )
