# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_distance <- function(l, m, N) {
    .Call('FastGP_rcpp_distance', PACKAGE = 'FastGP', l, m, N)
}

durbin <- function(r, N) {
    .Call('FastGP_durbin', PACKAGE = 'FastGP', r, N)
}

trench <- function(r, y, N) {
    .Call('FastGP_trench', PACKAGE = 'FastGP', r, y, N)
}

rcppeigen_invert_matrix <- function(A) {
    .Call('FastGP_rcppeigen_invert_matrix', PACKAGE = 'FastGP', A)
}

rcppeigen_get_diag <- function(A) {
    .Call('FastGP_rcppeigen_get_diag', PACKAGE = 'FastGP', A)
}

rcppeigen_get_det <- function(A) {
    .Call('FastGP_rcppeigen_get_det', PACKAGE = 'FastGP', A)
}

rcppeigen_get_chol <- function(A) {
    .Call('FastGP_rcppeigen_get_chol', PACKAGE = 'FastGP', A)
}

rcppeigen_get_chol_stable <- function(A) {
    .Call('FastGP_rcppeigen_get_chol_stable', PACKAGE = 'FastGP', A)
}

rcppeigen_get_chol_diag <- function(A) {
    .Call('FastGP_rcppeigen_get_chol_diag', PACKAGE = 'FastGP', A)
}

