.onAttach <- function(lib, pkg)
{
  packageStartupMessage('**************************************************************')
  packageStartupMessage('*                          COBRA v0.99.4                     *')
  packageStartupMessage('*                    Creator: Benjamin Guedj                 *')
  packageStartupMessage('*       http://www.lsta.upmc.fr/doct/guedj/index.html        *')
  packageStartupMessage('*     Please type citation("COBRA") for a citation guide     *')
  packageStartupMessage('*             _________         _________                    *')
  packageStartupMessage('*            /         \\       /         \\                   *')
  packageStartupMessage('*           /  /~~~~~\   \\     /  /~~~~~\   \\                  *')
  packageStartupMessage('*         /      \\   |  |     |  |     |  |                  *')
  packageStartupMessage('*        | <>  <> |  |  |     |  |     |  |                  *')
  packageStartupMessage('*        | <>  <> |  |  |     |  |     |  |         /        *')
  packageStartupMessage('*         \\      /   |  |     |  |     |  |       //         *')
  packageStartupMessage('*          (o  o)    \\  \\_____/  /     \\  \\_____/ /          *')
  packageStartupMessage('*           \\__/      \\         /       \\        /           *')
  packageStartupMessage('*            |         ~~~~~~~~~         ~~~~~~~~            *')
  packageStartupMessage('*            ^                                               *')
  packageStartupMessage('**************************************************************')
}
