library(faoutlier) 
nfact <- 3 
CFAmodel <- specifyModel("CFAmodel.txt")
mod1 <- sem(CFAmodel, data = holzinger) 
so <- summary(mod1)
MD1 <- robustMD(holzinger) 
MD2 <- robustMD(holzinger.outlier) 
OR1 <- obs.resid(holzinger, nfact) 
OR2 <- obs.resid(holzinger.outlier, nfact) 
GOF1 <- GOF(holzinger, nfact) 
GOF2 <- GOF(holzinger.outlier, nfact) 
gCD1 <- gCD(holzinger, nfact) 
gCD2 <- gCD(holzinger.outlier, nfact) 
gCD3 <- gCD(holzinger, CFAmodel) 
gCD4 <- gCD(holzinger.outlier, CFAmodel) 
FS1 <- forward.search(holzinger, nfact) 
FS2 <- forward.search(holzinger.outlier, nfact) 

save.image('objects.Rdata')
