## Generated by RcppR6: do not edit by hand
## Version: 0.2.3
## Hash: 8052bcaa3cd2755d6c121b68dced54fd

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib glmmsr
NULL

##' A vector of terms in the factorization of a graphical model,
##' of mixed continuous types.
##' @keywords internal
`continuous_beliefs` <- function() {
  continuous_beliefs__ctor()
}
.R6_continuous_beliefs <-
  R6::R6Class(
    "continuous_beliefs",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      append_glmm_belief = function(items, X, Zt, Lambdat, Lind, response, weights) {
        continuous_beliefs__append_glmm_belief(self, items, X, Zt, Lambdat, Lind, response, weights)
      },
      append_normal_belief = function(items, mean, precision) {
        continuous_beliefs__append_normal_belief(self, items, mean, precision)
      },
      size = function() {
        continuous_beliefs__size(self)
      }),
    active=list())

##' Parameters needed to calibrate the cluster tree
##' @keywords internal
`calibration_parameters` <- function() {
  calibration_parameters__ctor()
}
.R6_calibration_parameters <-
  R6::R6Class(
    "calibration_parameters",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      }),
    active=list(
      theta = function(value) {
        if (missing(value)) {
          calibration_parameters__theta__get(self)
        } else {
          calibration_parameters__theta__set(self, value)
        }
      },
      beta = function(value) {
        if (missing(value)) {
          calibration_parameters__beta__get(self)
        } else {
          calibration_parameters__beta__set(self, value)
        }
      },
      family = function(value) {
        if (missing(value)) {
          calibration_parameters__family__get(self)
        } else {
          calibration_parameters__family__set(self, value)
        }
      },
      link = function(value) {
        if (missing(value)) {
          calibration_parameters__link__get(self)
        } else {
          calibration_parameters__link__set(self, value)
        }
      },
      n_sparse_levels = function(value) {
        if (missing(value)) {
          calibration_parameters__n_sparse_levels__get(self)
        } else {
          calibration_parameters__n_sparse_levels__set(self, value)
        }
      },
      n_quadrature_points = function(value) {
        if (missing(value)) {
          calibration_parameters__n_quadrature_points__get(self)
        } else {
          calibration_parameters__n_quadrature_points__set(self, value)
        }
      }))

##' The beliefs for the clusters and sepsets of a cluster tree,
##' of mixed continuous types.
##' @param beliefs the vector of continuous beliefs to put on the cluster tree
##' @keywords internal
`cluster_graph` <- function(beliefs) {
  cluster_graph__ctor(beliefs)
}
.R6_cluster_graph <-
  R6::R6Class(
    "cluster_graph",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      compute_log_normalizing_constant = function(mean, precision, parameters) {
        cluster_graph__compute_log_normalizing_constant(self, mean, precision, parameters)
      }),
    active=list(
      width = function(value) {
        if (missing(value)) {
          cluster_graph__width__get(self)
        } else {
          stop("cluster_graph$width is read-only")
        }
      }))
