library(trackObjs)
source("trackObjs/inst/performanceTrials/funsForTesting.R")
options(width=100)
sessionInfo()
runSaveLoadTest("both", scale=10, clobber=TRUE)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=1)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=2)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=3)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=4)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=5)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=6)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=7)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=8)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=9)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=10)
runSaveLoadTest("both", scale=10, clobber=TRUE, obj.type=11)
# Remove the tracking dir
unlink("test1", recursive=TRUE)
