example(LIMTakapoto)
example(LIMRigaAutumn)
example(LIMRigaSpring)
example(LIMRigaSummer)
example(LIMBrouageMudflat)
example(LIMEverglades)
example(LIMScheldtIntertidal)
example(LIMCaliforniaSediment)
example(LIMBlending)
example(LIMEcoli)

