# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeCRsCpp <- function(x, exp, lambda) {
    .Call('algstat_computeCRsCpp', PACKAGE = 'algstat', x, exp, lambda)
}

computeG2sCpp <- function(x, exp) {
    .Call('algstat_computeG2sCpp', PACKAGE = 'algstat', x, exp)
}

computeNMsCpp <- function(x, exp) {
    .Call('algstat_computeNMsCpp', PACKAGE = 'algstat', x, exp)
}

computeUProbsCpp <- function(x) {
    .Call('algstat_computeUProbsCpp', PACKAGE = 'algstat', x)
}

computeX2sCpp <- function(x, exp) {
    .Call('algstat_computeX2sCpp', PACKAGE = 'algstat', x, exp)
}

metropolisCpp <- function(current, moves, iter, thin) {
    .Call('algstat_metropolisCpp', PACKAGE = 'algstat', current, moves, iter, thin)
}

