# From rebus.unicode

#' Unicode classes
#' 
#' See \code{\link[rebus.unicode]{Unicode}}.
#' @name Unicode
#' @aliases ADDITIONAL_ARROWS AEGEAN_NUMBERS ALCHEMICAL_SYMBOLS ALPHABETIC_PRESENTATION_FORMS ANCIENT_GREEK_MUSICAL_NOTATION ANCIENT_GREEK_NUMBERS ANCIENT_SYMBOLS ARABIC ARABIC_EXTENDED_A ARABIC_MATHEMATICAL_ALPHANUMERIC_SYMBOLS ARABIC_PRESENTATION_FORMS_A ARABIC_PRESENTATION_FORMS_B ARABIC_SUPPLEMENT ARMENIAN ARMENIAN_LIGATURES AVESTAN BALINESE BAMUN BAMUN_SUPPLEMENT BASSA_VAH BATAK BENGALI_AND_ASSAMESE BLOCK_ELEMENTS BOPOMOFO BOPOMOFO_EXTENDED BOX_DRAWING BRAHMI BRAILLE_PATTERNS BUGINESE BUHID BYZANTINE_MUSICAL_SYMBOLS CARD_SUITS CARIAN CAUCASIAN_ALBANIAN CHAKMA CHAM CHEROKEE CHESS_CHECKERS_DRAUGHTS CJK_COMPATIBILITY CJK_COMPATIBILITY_FORMS CJK_COMPATIBILITY_IDEOGRAPHS CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT CJK_IDEOGRAPHIC_DESCRIPTION_CHARACTERS CJK_STROKES CJK_SYMBOLS_AND_PUNCTUATION CJK_UNIFIED_IDEOGRAPHS CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D COMBINING_DIACRITIC_EXTENDED COMBINING_DIACRITIC_MARKS COMBINING_DIACRITIC_MARKS_FOR_SYMBOLS COMBINING_DIACRITIC_SUPPLEMENT COMBINING_HALF_MARKS COMMON_INDIC_NUMBER_FORMS CONTROL_PICTURES COPTIC COPTIC_EPACT_NUMBERS COUNTING_ROD_NUMERALS CUNEIFORM CUNEIFORM_NUMBERS_AND_PUNCTUATION CURRENCY_SYMBOLS CYPRIOT_SYLLABARY CYRILLIC CYRILLIC_EXTENDED_A CYRILLIC_EXTENDED_B CYRILLIC_SUPPLEMENT DESERET DEVANAGARI DEVANAGARI_EXTENDED DINGBATS DOMINO_TILES DUPLOYAN EGYPTIAN_HIEROGLYPHS ELBASAN EMOTICONS ENCLOSED_ALPHANUMERIC_SUPPLEMENT ENCLOSED_ALPHANUMERICS ENCLOSED_CJK_LETTERS_AND_MONTHS ENCLOSED_IDEOGRAPHIC_SUPPLEMENT ETHIOPIC ETHIOPIC_EXTENDED ETHIOPIC_EXTENDED_A ETHIOPIC_SUPPLEMENT FLOORS_AND_CEILINGS FULLWIDTH_ASCII_DIGITS FULLWIDTH_ASCII_PUNCTUATION GENERAL_PUNCTUATION GEOMETRIC_SHAPES GEOMETRIC_SHAPES_EXTENDED GEORGIAN GEORGIAN_SUPPLEMENT GLAGOLITIC GOTHIC GRANTHA GREEK_AND_COPTIC GREEK_EXTENDED GUJARATI GURMUKHI HALFWIDTH_AND_FULLWIDTH_FORMS HANGUL_COMPATIBILITY_JAMO HANGUL_JAMO HANGUL_JAMO_EXTENDED_A HANGUL_JAMO_EXTENDED_B HANGUL_SYLLABLES HANUNOO HEBREW HIRAGANA IMPERIAL_ARAMAIC INVISIBLE_OPERATORS IPA_EXTENSIONS JAPANESE_CHESS JAVANESE KAITHI KANA_SUPPLEMENT KANBUN KANGXI_RADICALS KANGXI_RADICALS_SUPPLEMENT KANNADA KATAKANA KATAKANA_PHONETIC_EXTENSIONS KAYAH_LI KHAROSHTHI KHMER KHMER_SYMBOLS KHOJKI KHUDAWADI LAO LATIN LATIN_1_PUNCTUATION LATIN_1_SUPPLEMENT LATIN_EXTENDED_A LATIN_EXTENDED_ADDITIONAL LATIN_EXTENDED_B LATIN_EXTENDED_C LATIN_EXTENDED_D LATIN_EXTENDED_E LATIN_LIGATURES LEPCHA LETTERLIKE_SYMBOLS LIMBU LINEAR_A LINEAR_B_IDEOGRAMS LINEAR_B_SYLLABARY LISU LYCIAN LYDIAN MAHAJANI MAHJONG_TILES MALAYALAM MANDAIC MANICHAEAN MATH_ARROWS MATHEMATICAL_ALPHANUMERIC_SYMBOLS MEETEI_MAYEK MEETEI_MAYEK_EXTENSIONS MENDE_KIKAKUI MEROITIC_CURSIVE MEROITIC_HIEROGLYPHS MIAO MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS MISCELLANEOUS_TECHNICAL MODI MODIFIER_TONE_LETTERS MONGOLIAN MRO MUSICAL_SYMBOLS MYANMAR MYANMAR_EXTENDED_A MYANMAR_EXTENDED_B NABATAEAN NEW_TAI_LUE NKO NUMBER_FORMS OGHAM OL_CHIKI OLD_ITALIC OLD_NORTH_ARABIAN OLD_PERMIC OLD_PERSIAN OLD_SOUTH_ARABIAN OLD_TURKIC OPTICAL_CHARACTER_RECOGNITION ORIYA ORNAMENTAL_DINGBATS OSMANYA PAHAWH_HMONG PAHLAVI_INSCRIPTIONAL PAHLAVI_PSALTER PALMYRENE PAU_CIN_HAU PHAGS_PA PHAISTOS_DISC PHOENICIAN PHONETIC_EXTENSIONS PHONETIC_EXTENSIONS_SUPPLEMENT PLAYING_CARDS PRIVATE_USE_AREA REJANG RUMI_NUMERAL_SYMBOLS RUNIC SAMARITAN SAURASHTRA SHARADA SHAVIAN SHORTHAND_FORMAT_CONTROLS SIDDHAM SINHALA SINHALA_ARCHAIC_NUMBERS SMALL_FORM_VARIANTS SORA_SOMPENG SPACING_MODIFIER_LETTERS SPECIALS SUNDANESE SUNDANESE_SUPPLEMENT SUPERSCRIPTS_AND_SUBSCRIPTS SUPPLEMENTAL_ARROWS_A SUPPLEMENTAL_MATHEMATICAL_OPERATORS SUPPLEMENTAL_PUNCTUATION SUPPLEMENTARY_PRIVATE_USE_AREA_A SUPPLEMENTARY_PRIVATE_USE_AREA_B SYLOTI_NAGRI SYRIAC TAGALOG TAGBANWA TAGS TAI_LE TAI_THAM TAI_VIET TAI_XUAN_JING_SYMBOLS TAKRI TAMIL TELUGU THAANA THAI TIBETAN TIFINAGH TIRHUTA TRANSPORT_AND_MAP_SYMBOLS UGARITIC UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED VAI VARIATION_SELECTORS VARIATION_SELECTORS_SUPPLEMENT VEDIC_EXTENSIONS VERTICAL_FORMS WARANG_CITI YI_RADICALS YI_SYLLABLES YIJING_HEXAGRAM_SYMBOLS YIJING_MONO_DI_AND_TRIGRAMS additional_arrows aegean_numbers alchemical_symbols alphabetic_presentation_forms ancient_greek_musical_notation ancient_greek_numbers ancient_symbols arabic arabic_extended_a arabic_mathematical_alphanumeric_symbols arabic_presentation_forms_a arabic_presentation_forms_b arabic_supplement armenian armenian_ligatures avestan balinese bamun bamun_supplement bassa_vah batak bengali_and_assamese block_elements bopomofo bopomofo_extended box_drawing brahmi braille_patterns buginese buhid byzantine_musical_symbols card_suits carian caucasian_albanian chakma cham cherokee chess_checkers_draughts cjk_compatibility cjk_compatibility_forms cjk_compatibility_ideographs cjk_compatibility_ideographs_supplement cjk_ideographic_description_characters cjk_strokes cjk_symbols_and_punctuation cjk_unified_ideographs cjk_unified_ideographs_extension_a cjk_unified_ideographs_extension_b cjk_unified_ideographs_extension_c cjk_unified_ideographs_extension_d combining_diacritic_extended combining_diacritic_marks combining_diacritic_marks_for_symbols combining_diacritic_supplement combining_half_marks common_indic_number_forms control_pictures coptic coptic_epact_numbers counting_rod_numerals cuneiform cuneiform_numbers_and_punctuation currency_symbols cypriot_syllabary cyrillic cyrillic_extended_a cyrillic_extended_b cyrillic_supplement deseret devanagari devanagari_extended dingbats domino_tiles duployan egyptian_hieroglyphs elbasan emoticons enclosed_alphanumeric_supplement enclosed_alphanumerics enclosed_cjk_letters_and_months enclosed_ideographic_supplement ethiopic ethiopic_extended ethiopic_extended_a ethiopic_supplement floors_and_ceilings fullwidth_ascii_digits fullwidth_ascii_punctuation general_punctuation geometric_shapes geometric_shapes_extended georgian georgian_supplement glagolitic gothic grantha greek_and_coptic greek_extended gujarati gurmukhi halfwidth_and_fullwidth_forms hangul_compatibility_jamo hangul_jamo hangul_jamo_extended_a hangul_jamo_extended_b hangul_syllables hanunoo hebrew hiragana imperial_aramaic invisible_operators ipa_extensions japanese_chess javanese kaithi kana_supplement kanbun kangxi_radicals kangxi_radicals_supplement kannada katakana katakana_phonetic_extensions kayah_li kharoshthi khmer khmer_symbols khojki khudawadi lao latin latin_1_punctuation latin_1_supplement latin_extended_a latin_extended_additional latin_extended_b latin_extended_c latin_extended_d latin_extended_e latin_ligatures lepcha letterlike_symbols limbu linear_a linear_b_ideograms linear_b_syllabary lisu lycian lydian mahajani mahjong_tiles malayalam mandaic manichaean math_arrows mathematical_alphanumeric_symbols meetei_mayek meetei_mayek_extensions mende_kikakui meroitic_cursive meroitic_hieroglyphs miao miscellaneous_mathematical_symbols_a miscellaneous_mathematical_symbols_b miscellaneous_symbols_and_pictographs miscellaneous_technical modi modifier_tone_letters mongolian mro musical_symbols myanmar myanmar_extended_a myanmar_extended_b nabataean new_tai_lue nko number_forms ogham ol_chiki old_italic old_north_arabian old_permic old_persian old_south_arabian old_turkic optical_character_recognition oriya ornamental_dingbats osmanya pahawh_hmong pahlavi_inscriptional pahlavi_psalter palmyrene pau_cin_hau phags_pa phaistos_disc phoenician phonetic_extensions phonetic_extensions_supplement playing_cards private_use_area rejang rumi_numeral_symbols runic samaritan saurashtra sharada shavian shorthand_format_controls siddham sinhala sinhala_archaic_numbers small_form_variants sora_sompeng spacing_modifier_letters specials sundanese sundanese_supplement superscripts_and_subscripts supplemental_arrows_a supplemental_mathematical_operators supplemental_punctuation supplementary_private_use_area_a supplementary_private_use_area_b syloti_nagri syriac tagalog tagbanwa tags tai_le tai_tham tai_viet tai_xuan_jing_symbols takri tamil telugu thaana thai tibetan tifinagh tirhuta transport_and_map_symbols ugaritic unified_canadian_aboriginal_syllabics unified_canadian_aboriginal_syllabics_extended vai variation_selectors variation_selectors_supplement vedic_extensions vertical_forms warang_citi yi_radicals yi_syllables yijing_hexagram_symbols yijing_mono_di_and_trigrams
#' @export ADDITIONAL_ARROWS
#' @export AEGEAN_NUMBERS
#' @export ALCHEMICAL_SYMBOLS
#' @export ALPHABETIC_PRESENTATION_FORMS
#' @export ANCIENT_GREEK_MUSICAL_NOTATION
#' @export ANCIENT_GREEK_NUMBERS
#' @export ANCIENT_SYMBOLS
#' @export ARABIC
#' @export ARABIC_EXTENDED_A
#' @export ARABIC_MATHEMATICAL_ALPHANUMERIC_SYMBOLS
#' @export ARABIC_PRESENTATION_FORMS_A
#' @export ARABIC_PRESENTATION_FORMS_B
#' @export ARABIC_SUPPLEMENT
#' @export ARMENIAN
#' @export ARMENIAN_LIGATURES
#' @export AVESTAN
#' @export BALINESE
#' @export BAMUN
#' @export BAMUN_SUPPLEMENT
#' @export BASSA_VAH
#' @export BATAK
#' @export BENGALI_AND_ASSAMESE
#' @export BLOCK_ELEMENTS
#' @export BOPOMOFO
#' @export BOPOMOFO_EXTENDED
#' @export BOX_DRAWING
#' @export BRAHMI
#' @export BRAILLE_PATTERNS
#' @export BUGINESE
#' @export BUHID
#' @export BYZANTINE_MUSICAL_SYMBOLS
#' @export CARD_SUITS
#' @export CARIAN
#' @export CAUCASIAN_ALBANIAN
#' @export CHAKMA
#' @export CHAM
#' @export CHEROKEE
#' @export CHESS_CHECKERS_DRAUGHTS
#' @export CJK_COMPATIBILITY
#' @export CJK_COMPATIBILITY_FORMS
#' @export CJK_COMPATIBILITY_IDEOGRAPHS
#' @export CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT
#' @export CJK_IDEOGRAPHIC_DESCRIPTION_CHARACTERS
#' @export CJK_STROKES
#' @export CJK_SYMBOLS_AND_PUNCTUATION
#' @export CJK_UNIFIED_IDEOGRAPHS
#' @export CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A
#' @export CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B
#' @export CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C
#' @export CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D
#' @export COMBINING_DIACRITIC_EXTENDED
#' @export COMBINING_DIACRITIC_MARKS
#' @export COMBINING_DIACRITIC_MARKS_FOR_SYMBOLS
#' @export COMBINING_DIACRITIC_SUPPLEMENT
#' @export COMBINING_HALF_MARKS
#' @export COMMON_INDIC_NUMBER_FORMS
#' @export CONTROL_PICTURES
#' @export COPTIC
#' @export COPTIC_EPACT_NUMBERS
#' @export COUNTING_ROD_NUMERALS
#' @export CUNEIFORM
#' @export CUNEIFORM_NUMBERS_AND_PUNCTUATION
#' @export CURRENCY_SYMBOLS
#' @export CYPRIOT_SYLLABARY
#' @export CYRILLIC
#' @export CYRILLIC_EXTENDED_A
#' @export CYRILLIC_EXTENDED_B
#' @export CYRILLIC_SUPPLEMENT
#' @export DESERET
#' @export DEVANAGARI
#' @export DEVANAGARI_EXTENDED
#' @export DINGBATS
#' @export DOMINO_TILES
#' @export DUPLOYAN
#' @export EGYPTIAN_HIEROGLYPHS
#' @export ELBASAN
#' @export EMOTICONS
#' @export ENCLOSED_ALPHANUMERIC_SUPPLEMENT
#' @export ENCLOSED_ALPHANUMERICS
#' @export ENCLOSED_CJK_LETTERS_AND_MONTHS
#' @export ENCLOSED_IDEOGRAPHIC_SUPPLEMENT
#' @export ETHIOPIC
#' @export ETHIOPIC_EXTENDED
#' @export ETHIOPIC_EXTENDED_A
#' @export ETHIOPIC_SUPPLEMENT
#' @export FLOORS_AND_CEILINGS
#' @export FULLWIDTH_ASCII_DIGITS
#' @export FULLWIDTH_ASCII_PUNCTUATION
#' @export GENERAL_PUNCTUATION
#' @export GEOMETRIC_SHAPES
#' @export GEOMETRIC_SHAPES_EXTENDED
#' @export GEORGIAN
#' @export GEORGIAN_SUPPLEMENT
#' @export GLAGOLITIC
#' @export GOTHIC
#' @export GRANTHA
#' @export GREEK_AND_COPTIC
#' @export GREEK_EXTENDED
#' @export GUJARATI
#' @export GURMUKHI
#' @export HALFWIDTH_AND_FULLWIDTH_FORMS
#' @export HANGUL_COMPATIBILITY_JAMO
#' @export HANGUL_JAMO
#' @export HANGUL_JAMO_EXTENDED_A
#' @export HANGUL_JAMO_EXTENDED_B
#' @export HANGUL_SYLLABLES
#' @export HANUNOO
#' @export HEBREW
#' @export HIRAGANA
#' @export IMPERIAL_ARAMAIC
#' @export INVISIBLE_OPERATORS
#' @export IPA_EXTENSIONS
#' @export JAPANESE_CHESS
#' @export JAVANESE
#' @export KAITHI
#' @export KANA_SUPPLEMENT
#' @export KANBUN
#' @export KANGXI_RADICALS
#' @export KANGXI_RADICALS_SUPPLEMENT
#' @export KANNADA
#' @export KATAKANA
#' @export KATAKANA_PHONETIC_EXTENSIONS
#' @export KAYAH_LI
#' @export KHAROSHTHI
#' @export KHMER
#' @export KHMER_SYMBOLS
#' @export KHOJKI
#' @export KHUDAWADI
#' @export LAO
#' @export LATIN
#' @export LATIN_1_PUNCTUATION
#' @export LATIN_1_SUPPLEMENT
#' @export LATIN_EXTENDED_A
#' @export LATIN_EXTENDED_ADDITIONAL
#' @export LATIN_EXTENDED_B
#' @export LATIN_EXTENDED_C
#' @export LATIN_EXTENDED_D
#' @export LATIN_EXTENDED_E
#' @export LATIN_LIGATURES
#' @export LEPCHA
#' @export LETTERLIKE_SYMBOLS
#' @export LIMBU
#' @export LINEAR_A
#' @export LINEAR_B_IDEOGRAMS
#' @export LINEAR_B_SYLLABARY
#' @export LISU
#' @export LYCIAN
#' @export LYDIAN
#' @export MAHAJANI
#' @export MAHJONG_TILES
#' @export MALAYALAM
#' @export MANDAIC
#' @export MANICHAEAN
#' @export MATH_ARROWS
#' @export MATHEMATICAL_ALPHANUMERIC_SYMBOLS
#' @export MEETEI_MAYEK
#' @export MEETEI_MAYEK_EXTENSIONS
#' @export MENDE_KIKAKUI
#' @export MEROITIC_CURSIVE
#' @export MEROITIC_HIEROGLYPHS
#' @export MIAO
#' @export MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A
#' @export MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B
#' @export MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS
#' @export MISCELLANEOUS_TECHNICAL
#' @export MODI
#' @export MODIFIER_TONE_LETTERS
#' @export MONGOLIAN
#' @export MRO
#' @export MUSICAL_SYMBOLS
#' @export MYANMAR
#' @export MYANMAR_EXTENDED_A
#' @export MYANMAR_EXTENDED_B
#' @export NABATAEAN
#' @export NEW_TAI_LUE
#' @export NKO
#' @export NUMBER_FORMS
#' @export OGHAM
#' @export OL_CHIKI
#' @export OLD_ITALIC
#' @export OLD_NORTH_ARABIAN
#' @export OLD_PERMIC
#' @export OLD_PERSIAN
#' @export OLD_SOUTH_ARABIAN
#' @export OLD_TURKIC
#' @export OPTICAL_CHARACTER_RECOGNITION
#' @export ORIYA
#' @export ORNAMENTAL_DINGBATS
#' @export OSMANYA
#' @export PAHAWH_HMONG
#' @export PAHLAVI_INSCRIPTIONAL
#' @export PAHLAVI_PSALTER
#' @export PALMYRENE
#' @export PAU_CIN_HAU
#' @export PHAGS_PA
#' @export PHAISTOS_DISC
#' @export PHOENICIAN
#' @export PHONETIC_EXTENSIONS
#' @export PHONETIC_EXTENSIONS_SUPPLEMENT
#' @export PLAYING_CARDS
#' @export PRIVATE_USE_AREA
#' @export REJANG
#' @export RUMI_NUMERAL_SYMBOLS
#' @export RUNIC
#' @export SAMARITAN
#' @export SAURASHTRA
#' @export SHARADA
#' @export SHAVIAN
#' @export SHORTHAND_FORMAT_CONTROLS
#' @export SIDDHAM
#' @export SINHALA
#' @export SINHALA_ARCHAIC_NUMBERS
#' @export SMALL_FORM_VARIANTS
#' @export SORA_SOMPENG
#' @export SPACING_MODIFIER_LETTERS
#' @export SPECIALS
#' @export SUNDANESE
#' @export SUNDANESE_SUPPLEMENT
#' @export SUPERSCRIPTS_AND_SUBSCRIPTS
#' @export SUPPLEMENTAL_ARROWS_A
#' @export SUPPLEMENTAL_MATHEMATICAL_OPERATORS
#' @export SUPPLEMENTAL_PUNCTUATION
#' @export SUPPLEMENTARY_PRIVATE_USE_AREA_A
#' @export SUPPLEMENTARY_PRIVATE_USE_AREA_B
#' @export SYLOTI_NAGRI
#' @export SYRIAC
#' @export TAGALOG
#' @export TAGBANWA
#' @export TAGS
#' @export TAI_LE
#' @export TAI_THAM
#' @export TAI_VIET
#' @export TAI_XUAN_JING_SYMBOLS
#' @export TAKRI
#' @export TAMIL
#' @export TELUGU
#' @export THAANA
#' @export THAI
#' @export TIBETAN
#' @export TIFINAGH
#' @export TIRHUTA
#' @export TRANSPORT_AND_MAP_SYMBOLS
#' @export UGARITIC
#' @export UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS
#' @export UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED
#' @export VAI
#' @export VARIATION_SELECTORS
#' @export VARIATION_SELECTORS_SUPPLEMENT
#' @export VEDIC_EXTENSIONS
#' @export VERTICAL_FORMS
#' @export WARANG_CITI
#' @export YI_RADICALS
#' @export YI_SYLLABLES
#' @export YIJING_HEXAGRAM_SYMBOLS
#' @export YIJING_MONO_DI_AND_TRIGRAMS
#' @export additional_arrows
#' @export aegean_numbers
#' @export alchemical_symbols
#' @export alphabetic_presentation_forms
#' @export ancient_greek_musical_notation
#' @export ancient_greek_numbers
#' @export ancient_symbols
#' @export arabic
#' @export arabic_extended_a
#' @export arabic_mathematical_alphanumeric_symbols
#' @export arabic_presentation_forms_a
#' @export arabic_presentation_forms_b
#' @export arabic_supplement
#' @export armenian
#' @export armenian_ligatures
#' @export avestan
#' @export balinese
#' @export bamun
#' @export bamun_supplement
#' @export bassa_vah
#' @export batak
#' @export bengali_and_assamese
#' @export block_elements
#' @export bopomofo
#' @export bopomofo_extended
#' @export box_drawing
#' @export brahmi
#' @export braille_patterns
#' @export buginese
#' @export buhid
#' @export byzantine_musical_symbols
#' @export card_suits
#' @export carian
#' @export caucasian_albanian
#' @export chakma
#' @export cham
#' @export cherokee
#' @export chess_checkers_draughts
#' @export cjk_compatibility
#' @export cjk_compatibility_forms
#' @export cjk_compatibility_ideographs
#' @export cjk_compatibility_ideographs_supplement
#' @export cjk_ideographic_description_characters
#' @export cjk_strokes
#' @export cjk_symbols_and_punctuation
#' @export cjk_unified_ideographs
#' @export cjk_unified_ideographs_extension_a
#' @export cjk_unified_ideographs_extension_b
#' @export cjk_unified_ideographs_extension_c
#' @export cjk_unified_ideographs_extension_d
#' @export combining_diacritic_extended
#' @export combining_diacritic_marks
#' @export combining_diacritic_marks_for_symbols
#' @export combining_diacritic_supplement
#' @export combining_half_marks
#' @export common_indic_number_forms
#' @export control_pictures
#' @export coptic
#' @export coptic_epact_numbers
#' @export counting_rod_numerals
#' @export cuneiform
#' @export cuneiform_numbers_and_punctuation
#' @export currency_symbols
#' @export cypriot_syllabary
#' @export cyrillic
#' @export cyrillic_extended_a
#' @export cyrillic_extended_b
#' @export cyrillic_supplement
#' @export deseret
#' @export devanagari
#' @export devanagari_extended
#' @export dingbats
#' @export domino_tiles
#' @export duployan
#' @export egyptian_hieroglyphs
#' @export elbasan
#' @export emoticons
#' @export enclosed_alphanumeric_supplement
#' @export enclosed_alphanumerics
#' @export enclosed_cjk_letters_and_months
#' @export enclosed_ideographic_supplement
#' @export ethiopic
#' @export ethiopic_extended
#' @export ethiopic_extended_a
#' @export ethiopic_supplement
#' @export floors_and_ceilings
#' @export fullwidth_ascii_digits
#' @export fullwidth_ascii_punctuation
#' @export general_punctuation
#' @export geometric_shapes
#' @export geometric_shapes_extended
#' @export georgian
#' @export georgian_supplement
#' @export glagolitic
#' @export gothic
#' @export grantha
#' @export greek_and_coptic
#' @export greek_extended
#' @export gujarati
#' @export gurmukhi
#' @export halfwidth_and_fullwidth_forms
#' @export hangul_compatibility_jamo
#' @export hangul_jamo
#' @export hangul_jamo_extended_a
#' @export hangul_jamo_extended_b
#' @export hangul_syllables
#' @export hanunoo
#' @export hebrew
#' @export hiragana
#' @export imperial_aramaic
#' @export invisible_operators
#' @export ipa_extensions
#' @export japanese_chess
#' @export javanese
#' @export kaithi
#' @export kana_supplement
#' @export kanbun
#' @export kangxi_radicals
#' @export kangxi_radicals_supplement
#' @export kannada
#' @export katakana
#' @export katakana_phonetic_extensions
#' @export kayah_li
#' @export kharoshthi
#' @export khmer
#' @export khmer_symbols
#' @export khojki
#' @export khudawadi
#' @export lao
#' @export latin
#' @export latin_1_punctuation
#' @export latin_1_supplement
#' @export latin_extended_a
#' @export latin_extended_additional
#' @export latin_extended_b
#' @export latin_extended_c
#' @export latin_extended_d
#' @export latin_extended_e
#' @export latin_ligatures
#' @export lepcha
#' @export letterlike_symbols
#' @export limbu
#' @export linear_a
#' @export linear_b_ideograms
#' @export linear_b_syllabary
#' @export lisu
#' @export lycian
#' @export lydian
#' @export mahajani
#' @export mahjong_tiles
#' @export malayalam
#' @export mandaic
#' @export manichaean
#' @export math_arrows
#' @export mathematical_alphanumeric_symbols
#' @export meetei_mayek
#' @export meetei_mayek_extensions
#' @export mende_kikakui
#' @export meroitic_cursive
#' @export meroitic_hieroglyphs
#' @export miao
#' @export miscellaneous_mathematical_symbols_a
#' @export miscellaneous_mathematical_symbols_b
#' @export miscellaneous_symbols_and_pictographs
#' @export miscellaneous_technical
#' @export modi
#' @export modifier_tone_letters
#' @export mongolian
#' @export mro
#' @export musical_symbols
#' @export myanmar
#' @export myanmar_extended_a
#' @export myanmar_extended_b
#' @export nabataean
#' @export new_tai_lue
#' @export nko
#' @export number_forms
#' @export ogham
#' @export ol_chiki
#' @export old_italic
#' @export old_north_arabian
#' @export old_permic
#' @export old_persian
#' @export old_south_arabian
#' @export old_turkic
#' @export optical_character_recognition
#' @export oriya
#' @export ornamental_dingbats
#' @export osmanya
#' @export pahawh_hmong
#' @export pahlavi_inscriptional
#' @export pahlavi_psalter
#' @export palmyrene
#' @export pau_cin_hau
#' @export phags_pa
#' @export phaistos_disc
#' @export phoenician
#' @export phonetic_extensions
#' @export phonetic_extensions_supplement
#' @export playing_cards
#' @export private_use_area
#' @export rejang
#' @export rumi_numeral_symbols
#' @export runic
#' @export samaritan
#' @export saurashtra
#' @export sharada
#' @export shavian
#' @export shorthand_format_controls
#' @export siddham
#' @export sinhala
#' @export sinhala_archaic_numbers
#' @export small_form_variants
#' @export sora_sompeng
#' @export spacing_modifier_letters
#' @export specials
#' @export sundanese
#' @export sundanese_supplement
#' @export superscripts_and_subscripts
#' @export supplemental_arrows_a
#' @export supplemental_mathematical_operators
#' @export supplemental_punctuation
#' @export supplementary_private_use_area_a
#' @export supplementary_private_use_area_b
#' @export syloti_nagri
#' @export syriac
#' @export tagalog
#' @export tagbanwa
#' @export tags
#' @export tai_le
#' @export tai_tham
#' @export tai_viet
#' @export tai_xuan_jing_symbols
#' @export takri
#' @export tamil
#' @export telugu
#' @export thaana
#' @export thai
#' @export tibetan
#' @export tifinagh
#' @export tirhuta
#' @export transport_and_map_symbols
#' @export ugaritic
#' @export unified_canadian_aboriginal_syllabics
#' @export unified_canadian_aboriginal_syllabics_extended
#' @export vai
#' @export variation_selectors
#' @export variation_selectors_supplement
#' @export vedic_extensions
#' @export vertical_forms
#' @export warang_citi
#' @export yi_radicals
#' @export yi_syllables
#' @export yijing_hexagram_symbols
#' @export yijing_mono_di_and_trigrams
NULL 
