source("R/fun.R")
source("R/xtabularAssay.R")
source("R/xtablesAssay.R")
source("R/xtableHead.R")
source("R/xtableLabels.R")
source("R/xtableLatinSquare.R")
source("R/xtableTableCS.R")
source("R/xtableTable.R")
source("R/xtableModel.R")
source("R/xtableAnova.R")
source("R/xtableParameters.R")
source("R/xtableValidity.R")
source("R/xtablePotency.R")
# source("R/xtablePotency11.R")
# source("R/xtablePotency13.R")
# source("R/xtablePotencyX1.R")
# source("R/xtablePotency23.R")
# source("R/xtablePotencyXX.R")

