if (getRversion() >= '2.15.1') globalVariables(c('dataTab', 'dataoptionsFrame', 'smoothingTab',
'ciTab', 'cigeneralFrame', 'cibootstrapFrame', 'aucTab', 'partialaucFrame', 'optionsTab',
'informationFrame', 'notebook', 'narmVariable', 'percentVariable', 'directionrbVariable',
'smoothingmethodrbVariable', 'smoothinbandwidthrbVariable', 'bandwidthwindowrbVariable',
'distributioncasesrbVariable', 'distributioncontrolsrbVariable', 'cicomputeVariable',
'cimethodrbVariable', 'cityperbVariable', 'cithresholdsrbVariable', 'cibootstratifiedVariable',
'aucVariable', 'partialaucVariable', 'partialfocusVariable', 'partialcorrectVariable', 'addVariable',
'plotVariable', 'smoothVariable', 'printaucVariable', 'aucpolygonVariable', 'maxaucpolygonVariable',
'gridVariable', 'identityVariable', 'ciplotVariable', 'valuesVariable', 'printthresrbVariable',
'ciplottyperbVariable', '.depname', 'directionrbFrame', 'smoothingmethodrbFrame',
'smoothinbandwidthrbFrame', 'bandwidthwindowrbFrame', 'distributioncontrolsrbFrame',
'distributioncasesrbFrame', 'cimethodrbFrame', 'cityperbFrame', 'cithresholdsrbFrame',
'partialfocusFrame', 'generalaucFrame', 'optionsFrame', 'aucpolygonFrame', 'printthresrbFrame',
'ciplottyperbFrame', 'top', 'testmethodrbVariable', 'testalternativerbVariable',
'smoothingmethod2rbVariable', 'smoothinbandwidth2rbVariable', 'bandwidthwindow2rbVariable',
'distributioncases2rbVariable', 'distributioncontrols2rbVariable', 'pvalueVariable',
'testmethodrbFrame', 'testalternativerbFrame', 'smoothingmethod2rbFrame', 'smoothinbandwidth2rbFrame',
'distributioncontrols2rbFrame', 'distributioncases2rbFrame', 'Reclassification', 'buttonsFrame',
'colorizeVariable', 'printrocVariable', 'printcutoffsVariable', 'predictions', 'classifTableVariable',
'percentCorrectVariable', 'aditionaloptionsFrame'))
