# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resample_stratum <- function(clusters, B) {
    .Call('surveybootstrap_resample_stratum', PACKAGE = 'surveybootstrap', clusters, B)
}

