detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(3, 1, 1)
hParam <- c(1, 1, 3)
sampleInput <- rskewlap(100, param = gParam)
qqskewlap(sampleInput, param = gParam)
dev.new()
ppskewlap(sampleInput, param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
dev.new()
qqskewlap(sampleInput, Theta = hParam)
dev.new()
ppskewlap(sampleInput, Theta = hParam)
detach("package:HyperbolicDist")
