detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(2, 1, 1)
hParam <- c(1, 2, 1)
gmResult <- gigMean(param = gParam)
gvResult <- gigVar(param = gParam)
gsResult <- gigSkew(param = gParam)
gkResult <- gigKurt(param = gParam)
gmoResult <- gigMode(param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hmResult <- gigMean(Theta = hParam)
hvResult <- gigVar(Theta = hParam)
hsResult <- gigSkew(Theta = hParam)
hkResult <- gigKurt(Theta = hParam)
hmoResult <- gigMode(Theta = hParam)
detach("package:HyperbolicDist")

checkEqual(gmResult, hmResult, "gigMean")
checkEqual(gvResult, hvResult, "gigVar")
checkEqual(gsResult, hsResult, "gigSkew")
checkEqual(gkResult, hkResult, "gigKurt")
checkEqual(gmoResult, hmoResult, "gigMode")
