detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(0, 1, 3, 1, 0.5)
hParam <- c(0.5, 3, 1, 1, 0)
g0Result <- ghypMom(1, param = gParam)
g1Result <- ghypMom(2, param = gParam)
g2Result <- ghypMom(10, param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
h0Result <- ghypMom(1, Theta = hParam)
h1Result <- ghypMom(2, Theta = hParam)
h2Result <- ghypMom(10, Theta = hParam)
detach("package:HyperbolicDist")

gResult <- c(g0Result, g1Result, g2Result)
hResult <- c(h0Result, h1Result, h2Result)

checkEqual(gResult, hResult, "ghypMom")
