detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(2, 1, 1)
hParam <- c(1, 2, 1)
g0Result <- gigMom(1, param = gParam)
g1Result <- gigMom(2, param = gParam)
g2Result <- gigMom(10, param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
h0Result <- gigMom(1, Theta = hParam)
h1Result <- gigMom(2, Theta = hParam)
h2Result <- gigMom(10, Theta = hParam)
detach("package:HyperbolicDist")

gResult <- c(g0Result, g1Result, g2Result)
hResult <- c(h0Result, h1Result, h2Result)

checkEqual(gResult, hResult, "gigMom")
