detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(2, 1, 1)
hParam <- c(1, 2, 1)
sampleInput <- rgig(100, param = gParam)
gdResult <- dgig(sampleInput, param = gParam)
gpResult <- pgig(seq(-2, 5, 0.2), param = gParam)
gqResult <- qgig(seq(0.1, 0.9, 0.1), param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hdResult <- dgig(sampleInput, Theta = hParam)
hpResult <- pgig(seq(-2, 5, 0.2), Theta = hParam)
hqResult <- qgig(seq(0.1, 0.9, 0.1), Theta = hParam)
detach("package:HyperbolicDist")

checkEqual(gdResult, hdResult, "dgig")
checkEqual(gpResult, hpResult, "pgig")
checkEqual(gqResult, hqResult, "qgig")
