detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(0, 1, 3, 1, 0.5)
hParam <- c(0.5, 3, 1, 1, 0)
sampleInput <- rghyp(100, param = gParam)
qqghyp(sampleInput, param = gParam)
dev.new()
ppghyp(sampleInput, param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
dev.new()
qqghyp(sampleInput, Theta = hParam)
dev.new()
ppghyp(sampleInput, Theta = hParam)
detach("package:HyperbolicDist")
