detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(0, 1, 3, 1)
hyperbData <- rhyperb(1000, param = gParam)
hParam <- hyperbChangePars(2, 1, gParam, noNames = TRUE)
hParam <- c(hParam[3], hParam[4], hParam[2], hParam[1])
gResult <- hyperbCvMTest(hyperbData, param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hResult <- hyperbCvMTest(hyperbData, Theta = hParam)
detach("package:HyperbolicDist")

checkEqual(gResult, hResult, "ghypCalcRange")
