detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(1, 2, 1.5, 1)
hParam <- hyperbChangePars(2, 1, gParam, noNames = TRUE)
hParam <- c(hParam[3], hParam[4], hParam[2], hParam[1])
gmResult <- hyperbMean(param = gParam)
gvResult <- hyperbVar(param = gParam)
gsResult <- hyperbSkew(param = gParam)
gkResult <- hyperbKurt(param = gParam)
gmoResult <- hyperbMode(param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hmResult <- hyperbMean(Theta = hParam)
hvResult <- hyperbVar(Theta = hParam)
hsResult <- hyperbSkew(Theta = hParam)
hkResult <- hyperbKurt(Theta = hParam)
hmoResult <- hyperbMode(Theta = hParam)
detach("package:HyperbolicDist")

checkEqual(gmResult, hmResult, "hyperbMean")
checkEqual(gvResult, hvResult, "hyperbVar")
checkEqual(gsResult, hsResult, "hyperbSkew")
checkEqual(gkResult, hkResult, "hyperbKurt")
checkEqual(gmoResult, hmoResult, "hyperbMode")
