detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(2, 1, 1)
hParam <- c(1, 2, 1)
sampleInput <- rgig(100, param = gParam)
qqgig(sampleInput, param = gParam)
dev.new()
ppgig(sampleInput, param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
dev.new()
qqgig(sampleInput, Theta = hParam)
dev.new()
ppgig(sampleInput, Theta = hParam)
detach("package:HyperbolicDist")
