setClass("powerLongSurv",
    representation(
        title = "character",
        subtitle = "character",
        t = "vector",
        p = "vector",
        N = "integer",
        nevents = "integer",
        censr = "numeric",
        tmedian = "numeric",
        meantf = "numeric",
        SigmaTheta = "matrix",
        ordtraj = "integer",
        BSigma = "matrix",
        beta = "numeric",
        alpha = "numeric",
        power = "numeric"),
    prototype(
      title = "No Calculation Performed",
      subtitle = "No Calcultion Performed",
      t = numeric(1),
      p = numeric(1),
      N = 0L,
      nevents = 0L,
      censr = 0.0,
      tmedian = 0.0,
      meantf = 0.0,
      SigmaTheta = matrix(0,1,1),
      ordtraj = 0L,
      BSigma = matrix(0,1,1),
      beta = 0.0,
      alpha = 0.0,
      power = 0.0)
)
