retrosheetFields <- structure(list(eventInner = list(NULL, NULL, c("category", "info"
), c("retroID", "name", "team", "batPos", "fieldPos"), c("inning",
"team", "retroID", "count", "pitches", "play"), NULL, c("retroID",
"name", "team", "batPos", "fieldPos"), c("projCode", "retroID",
"ER")), eventOuter = c("id", "version", "info", "start", "play",
"com", "sub", "data"), franchise = c("FranchiseID", "OtherID",
"Lg", "Div", "Loc", "Nick1", "Nick2", "GmFirst", "GmLast", "City",
"State"), gamelog = c("Date", "DblHdr", "Day", "VisTm", "VisTmLg",
"VisTmGNum", "HmTm", "HmTmLg", "HmTmGNum", "VisRuns", "HmRuns",
"NumOuts", "DayNight", "Completion", "Forfeit", "Protest", "ParkID",
"Attendance", "Duration", "VisLine", "HmLine", "VisAB", "VisH",
"VisD", "VisT", "VisHR", "VisRBI", "VisSH", "VisSF", "VisHBP",
"VisBB", "VisIBB", "VisK", "VisSB", "VisCS", "VisGDP", "VisCI",
"VisLOB", "VisPs", "VisER", "VisTER", "VisWP", "VisBalks", "VisPO",
"VisA", "VisE", "VisPassed", "VisDB", "VisTP", "HmAB", "HmH",
"HmD", "HmT", "HmHR", "HmRBI", "HmSH", "HmSF", "HmHBP", "HmBB",
"HmIBB", "HmK", "HmSB", "HmCS", "HmGDP", "HmCI", "HmLOB", "HmPs",
"HmER", "HmTER", "HmWP", "HmBalks", "HmPO", "HmA", "HmE", "HmPass",
"HmDB", "HmTP", "UmpHID", "UmpHNm", "Ump1BID", "Ump1BNm", "Ump2BID",
"Ump2BNm", "Ump3BID", "Ump3BNm", "UmpLFID", "UmpLFNm", "UmpRFID",
"UmpRFNm", "VisMgrID", "VisMgrNm", "HmMgrID", "HmMgrNm", "WinPID",
"WinPNm", "PID", "PNAme", "SavePID", "SavePNm", "GWinRBIID",
"GWinRBINm", "VisStPchID", "VisStPchNm", "HmStPchID", "HmStPchNm",
"VisBat1ID", "VisBat1Nm", "VisBat1Pos", "VisBat2ID", "VisBat2Nm",
"VisBat2Pos", "VisBat3ID", "VisBat3Nm", "VisBat3Pos", "VisBat4ID",
"VisBat4Nm", "VisBat4Pos", "VisBat5ID", "VisBat5Nm", "VisBat5Pos",
"VisBat6ID", "VisBat6Nm", "VisBat6Pos", "VisBat7ID", "VisBat7Nm",
"VisBat7Pos", "VisBat8ID", "VisBat8Nm", "VisBat8Pos", "VisBat9ID",
"VisBat9Nm", "VisBat9Pos", "HmBat1ID", "HmBat1Nm", "HmBat1Pos",
"HmBat2ID", "HmBat2Nm", "HmBat2Pos", "HmBat3ID", "HmBat3Nm",
"HmBat3Pos", "HmBat4ID", "HmBat4Nm", "HmBat4Pos", "HmBat5ID",
"HmBat5Nm", "HmBat5Pos", "HmBat6ID", "HmBat6Nm", "HmBat6Pos",
"HmBat7ID", "HmBat7Nm", "HmBat7Pos", "HmBat8ID", "HmBat8Nm",
"HmBat8Pos", "HmBat9ID", "HmBat9Nm", "HmBat9Pos", "Additional",
"Acquisition"), roster = c("retroID", "Last", "First", "Bat",
"Throw", "Team", "Pos"), schedule = c("Date", "GameNo", "Day",
"VisTeam", "VisLg", "VisGmNo", "HmTeam", "HmLg", "HmGmNo", "TimeOfDay",
"Postponed", "Makeup")), .Names = c("eventInner", "eventOuter",
"franchise", "gamelog", "roster", "schedule"))
