inpbox_flow_options <-
function(inp){
	table<-gtkTable(rows=16,columns=10,homogeneous=FALSE)
	diag_label<-gtkVBox()
	labelgp<-list()
	labelgp$t1<-gtkLabel('Monomer          ')
	labelgp$t2<-gtkLabel('Initiator            ')
	labelgp$t3<-gtkLabel('Solvent              ')
	labelgp$t4<-gtkLabel('Inhibitor             ')
	labelgp$t5<-gtkLabel('CT Agent           ')
	labelgp$t6<-gtkLabel('CCT Agent        ')
	labelgp$t7<-gtkLabel('Cation              ')
	labelgp$t8<-gtkLabel('Output              ')
	sapply(labelgp,diag_label$packStart)
	diag_entry<-gtkVBox()
	entrygp<-list()
	entrygp$e1<-gtkEntryNew()
	entrygp$e1$SetText(inp[[1]][1])
	entrygp$e2<-gtkEntryNew()
	entrygp$e2$SetText(inp[[2]][1])
	entrygp$e3<-gtkEntryNew()
	entrygp$e3$SetText(inp[[3]][1])
	entrygp$e4<-gtkEntryNew()
	entrygp$e4$SetText(inp[[4]][1])
	entrygp$e5<-gtkEntryNew()
	entrygp$e5$SetText(inp[[5]][1])
	entrygp$e6<-gtkEntryNew()
	entrygp$e6$SetText(inp[[6]][1])
	entrygp$e7<-gtkEntryNew()
	entrygp$e7$SetText(inp[[7]][1])
	entrygp$e8<-gtkEntryNew()
	entrygp$e8$SetText(inp[[8]][1])
	sapply(entrygp,diag_entry$packStart)
	diag_entry1<-gtkVBox()
	entrygp1<-list()
	entrygp1$e1<-gtkEntryNew()
	entrygp1$e1$SetText(inp[[1]][2])
	entrygp1$e2<-gtkEntryNew()
	entrygp1$e2$SetText(inp[[2]][2])
	entrygp1$e3<-gtkEntryNew()
	entrygp1$e3$SetText(inp[[3]][2])
	entrygp1$e4<-gtkEntryNew()
	entrygp1$e4$SetText(inp[[4]][2])
	entrygp1$e5<-gtkEntryNew()
	entrygp1$e5$SetText(inp[[5]][2])
	entrygp1$e6<-gtkEntryNew()
	entrygp1$e6$SetText(inp[[6]][2])
	entrygp1$e7<-gtkEntryNew()
	entrygp1$e7$SetText(inp[[7]][2])
	entrygp1$e8<-gtkEntryNew()
	entrygp1$e8$SetText(inp[[8]][2])
	sapply(entrygp1,diag_entry1$packStart)
	diag_entry2<-gtkVBox()
	entrygp2<-list()
	entrygp2$e1<-gtkEntryNew()
	entrygp2$e1$SetText(inp[[1]][3])
	entrygp2$e2<-gtkEntryNew()
	entrygp2$e2$SetText(inp[[2]][3])
	entrygp2$e3<-gtkEntryNew()
	entrygp2$e3$SetText(inp[[3]][3])
	entrygp2$e4<-gtkEntryNew()
	entrygp2$e4$SetText(inp[[4]][3])
	entrygp2$e5<-gtkEntryNew()
	entrygp2$e5$SetText(inp[[5]][3])
	entrygp2$e6<-gtkEntryNew()
	entrygp2$e6$SetText(inp[[6]][3])
	entrygp2$e7<-gtkEntryNew()
	entrygp2$e7$SetText(inp[[7]][3])
	entrygp2$e8<-gtkEntryNew()
	entrygp2$e8$SetText(inp[[8]][3])
	sapply(entrygp2,diag_entry2$packStart)
	submit_hbox<-gtkHBox()
	button_ok<-gtkButton("OK")
	button_canc<-gtkButton("Cancel")
	submit_hbox$packStart(button_ok,expand=TRUE)
	submit_hbox$packEnd(button_canc,expand=TRUE)
	gSignalConnect(button_ok,"clicked",f=function(button_ok){
	button_ok$setData('ans',list(
	as.numeric(c(entrygp$e1$getText(),entrygp1$e1$getText(),entrygp2$e1$getText())),
	as.numeric(c(entrygp$e2$getText(),entrygp1$e2$getText(),entrygp2$e2$getText())),
	as.numeric(c(entrygp$e3$getText(),entrygp1$e3$getText(),entrygp2$e3$getText())),
	as.numeric(c(entrygp$e4$getText(),entrygp1$e4$getText(),entrygp2$e4$getText())),
	as.numeric(c(entrygp$e5$getText(),entrygp1$e5$getText(),entrygp2$e5$getText())),
	as.numeric(c(entrygp$e6$getText(),entrygp1$e6$getText(),entrygp2$e6$getText())),
	as.numeric(c(entrygp$e7$getText(),entrygp1$e7$getText(),entrygp2$e7$getText())),
	as.numeric(c(entrygp$e8$getText(),entrygp1$e8$getText(),entrygp2$e8$getText())))
	)
	gtkMainQuit()
	}
	)
	gSignalConnect(button_canc,"clicked",f=function(button_canc){
	button_ok$setData('ans',NULL)
	gtkMainQuit()
	}
	)
	diag_align<-gtkAlignment(xalign=0)
	diag_align$add(diag_label)
	diag_align1<-gtkAlignment(xalign=0)
	diag_align1$add(diag_entry)
	diag_align2<-gtkAlignment(xalign=0)
	diag_align2$add(diag_entry1)
	diag_align3<-gtkAlignment(xalign=0)
	diag_align3$add(diag_entry2)
	lbtitle<-gtkLabel('                   Flow (kg/min)                            Start Time (min)                                End Time (min)')
	lbblanc<-gtkLabel(' ')
	table$attach(lbtitle,left.attach=1,8,top.attach=1,2,xoptions=c('expand','fill'),yoptions=c('expand','fill'))
	table$attach(lbblanc,left.attach=1,8,top.attach=2,3,xoptions=c('expand','fill'),yoptions=c('expand','fill'))
	table$attach(diag_align,left.attach=1,2,top.attach=3,4,xoptions=c('expand','fill'),yoptions=c('expand','fill'))
	table$attach(diag_align1,left.attach=3,4,top.attach=3,4,xoptions=c('expand','fill'),yoptions=c('expand','fill'))
	table$attach(diag_align2,left.attach=5,6,top.attach=3,4,xoptions=c('expand','fill'),yoptions=c('expand','fill'))
	table$attach(diag_align3,left.attach=7,8,top.attach=3,4,xoptions=c('expand','fill'),yoptions=c('expand','fill'))
	table$attach(submit_hbox,left.attach=1,8,top.attach=15,16,xoptions=c('expand','fill'),yoptions=c('expand','fill'))
	table$setColSpacing(0,5)
	window<-gtkWindow(show=FALSE)
	window['border-width']<-14
	window$setTitle('In and Out Flow Conditions')
	window$SetDeletable(FALSE)
	window$SetResizable(FALSE)
	window$add(table)
	window$showAll()
	gtkMain()
	ans<-button_ok$GetData('ans')
	window$Destroy()
	return(ans)
}
