save.file.summary <-
function(result,name,app=TRUE,mod1,mod2) {
  cat("\n",
      "------------------------------------------------\n",
      mod1,"\n",
      "------------------------------------------------\n",
      "Area:                               ",result$Area1,"\n",
      "Standard Error:                     ",result$SE1,"\n",
      "Area through Trapezoidal Method:    ",result$TrapArea1,"\n",
      "CI Upper bound (Percentil Method):  ",result$ICUB1,"\n",
      "CI Lower bound (Percentil Method):  ",result$ICLB1,"\n",
      "------------------------------------------------\n",
      "\n",
      "------------------------------------------------\n",
      mod2,"\n",
      "------------------------------------------------\n",
      "Area:                               ",result$Area2,"\n",
      "Standard Error:                     ",result$SE2,"\n",
      "Area through Trapezoidal Method:    ",result$TrapArea2,"\n",
      "CI Upper bound (Percentil Method):  ",result$ICUB2,"\n",
      "CI Lower bound (Percentil Method):  ",result$ICLB2,"\n",
      "------------------------------------------------\n",
      "\n",
      "Correlation Coefficient between areas:  ", result$CorrCoef,"\n",
      "\n",
      "TEST OF DIFFERENCES\n",
      "Z stats:  ", result$zstats,"\n",
      "p-value:  ", result$pvalue1,"\n",
      "\n",
      "Sum of Global Areas Differences (TS):  ", result$diff,"\n",
      "CI Upper bound (Percentil Method):  ",result$ICUBDiff,"\n",
      "CI Lower bound (Percentil Method):  ",result$ICLBDiff,"\n",
      "\n",
      "Number of Crossings:  ", result$nCross,"\n",
      file=paste(name,"Results.txt"),append=app)
}
